/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import static java.awt.Color.pink;
import static java.awt.Color.white;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author andre
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIcon();
        this.setResizable(false);

    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/main/log.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo4 = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        serpienteslogo = new javax.swing.JLabel();
        cont5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        logo_gif = new javax.swing.JLabel();
        sopalogo = new javax.swing.JLabel();
        blackjacklogo = new javax.swing.JLabel();
        cont = new javax.swing.JLabel();
        rompecabezaslogo = new javax.swing.JLabel();
        carreraslogo = new javax.swing.JLabel();
        cont2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cont3 = new javax.swing.JLabel();
        cont4 = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        blackjack1 = new javax.swing.JLabel();
        carreras = new javax.swing.JLabel();
        rompecabezas = new javax.swing.JLabel();
        sopa = new javax.swing.JLabel();
        serpientes = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        marco = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 1000), new java.awt.Dimension(0, 1000), new java.awt.Dimension(32767, 1000));
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo4.setBackground(new java.awt.Color(46, 44, 48));
        fondo4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText(">>Salir<<");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });
        fondo4.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, 210, -1));
        salir.getAccessibleContext().setAccessibleName("salir");
        salir.getAccessibleContext().setAccessibleParent(salir);

        serpienteslogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/snake.png"))); // NOI18N
        serpienteslogo.setToolTipText("");
        serpienteslogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serpienteslogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serpienteslogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                serpienteslogoMouseExited(evt);
            }
        });
        fondo4.add(serpienteslogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 350, -1, 150));

        cont5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/conta.png"))); // NOI18N
        fondo4.add(cont5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 310, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        fondo4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 330, 180, 180));

        logo_gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/cristallogo.gif"))); // NOI18N
        fondo4.add(logo_gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        sopalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sopita.png"))); // NOI18N
        sopalogo.setToolTipText("");
        sopalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sopalogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sopalogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sopalogoMouseExited(evt);
            }
        });
        fondo4.add(sopalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 450, -1, -1));

        blackjacklogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/blackj.png"))); // NOI18N
        blackjacklogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blackjacklogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blackjacklogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                blackjacklogoMouseExited(evt);
            }
        });
        fondo4.add(blackjacklogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 180, 170));

        cont.setBackground(new java.awt.Color(255, 204, 204));
        cont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/conta.png"))); // NOI18N
        cont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contMouseExited(evt);
            }
        });
        fondo4.add(cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        rompecabezaslogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/puzzle (1).png"))); // NOI18N
        rompecabezaslogo.setToolTipText("");
        rompecabezaslogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rompecabezaslogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rompecabezaslogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rompecabezaslogoMouseExited(evt);
            }
        });
        fondo4.add(rompecabezaslogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        carreraslogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/finish.png"))); // NOI18N
        carreraslogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carreraslogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carreraslogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carreraslogoMouseExited(evt);
            }
        });
        fondo4.add(carreraslogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));

        cont2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/conta.png"))); // NOI18N
        fondo4.add(cont2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        fondo4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 180, 180));

        cont3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/conta.png"))); // NOI18N
        fondo4.add(cont3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, -1));

        cont4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/conta.png"))); // NOI18N
        fondo4.add(cont4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, -1, -1));

        Panel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        fondo4.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 180, 180));

        jPanel3.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        fondo4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 180, 180));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        fondo4.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 430, 180, 180));

        blackjack1.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        blackjack1.setForeground(new java.awt.Color(255, 255, 255));
        blackjack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/blac.png"))); // NOI18N
        blackjack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blackjack1MouseEntered(evt);
            }
        });
        fondo4.add(blackjack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        carreras.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        carreras.setForeground(new java.awt.Color(255, 255, 255));
        carreras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/cras (1).png"))); // NOI18N
        fondo4.add(carreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        rompecabezas.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        rompecabezas.setForeground(new java.awt.Color(255, 255, 255));
        rompecabezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/rpc.png"))); // NOI18N
        fondo4.add(rompecabezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, -1, -1));

        sopa.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        sopa.setForeground(new java.awt.Color(255, 255, 255));
        sopa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/sp.png"))); // NOI18N
        fondo4.add(sopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, -1, -1));

        serpientes.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        serpientes.setForeground(new java.awt.Color(255, 255, 255));
        serpientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/ssp.png"))); // NOI18N
        fondo4.add(serpientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 540, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/brillo.gif"))); // NOI18N
        fondo4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/hcris.gif"))); // NOI18N
        fondo4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 140, 120));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/brillo.gif"))); // NOI18N
        fondo4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/logo2.png"))); // NOI18N
        fondo4.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        marco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(141, 237, 230), new java.awt.Color(236, 203, 237), new java.awt.Color(204, 51, 255), new java.awt.Color(208, 229, 253)));
        fondo4.add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1270, 660));
        fondo4.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, -250, 320, 1150));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/da853c3-f1085771-170a-46f5-ad04-2773674a9c05.gif"))); // NOI18N
        fondo4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 140, 120));

        jLabel11.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(">>Selecciona un juego<<");
        fondo4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fondo4, javax.swing.GroupLayout.PREFERRED_SIZE, 1303, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo4, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        salir.setLocation(530, 615);
        salir.setForeground(pink);
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        salir.setLocation(530, 620);
        salir.setForeground(white);
    }//GEN-LAST:event_salirMouseExited

    private void serpienteslogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serpienteslogoMouseClicked
        juegos.serpientes_y_escaleras snake = new juegos.serpientes_y_escaleras();
        this.dispose();
        snake.setVisible(true);
    }//GEN-LAST:event_serpienteslogoMouseClicked

    private void serpienteslogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serpienteslogoMouseEntered
        serpienteslogo.setLocation(1050, 345);
    }//GEN-LAST:event_serpienteslogoMouseEntered

    private void serpienteslogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serpienteslogoMouseExited
        serpienteslogo.setLocation(1050, 350);
    }//GEN-LAST:event_serpienteslogoMouseExited

    private void sopalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sopalogoMouseClicked
        juegos.sopadeletras sopa = new juegos.sopadeletras();
        this.dispose();
        sopa.setVisible(true);
    }//GEN-LAST:event_sopalogoMouseClicked

    private void sopalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sopalogoMouseEntered
        sopalogo.setLocation(810, 445);
    }//GEN-LAST:event_sopalogoMouseEntered

    private void sopalogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sopalogoMouseExited
        sopalogo.setLocation(810, 450);
    }//GEN-LAST:event_sopalogoMouseExited

    private void blackjacklogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blackjacklogoMouseClicked
        juegos.blackjack bl = new juegos.blackjack();
        this.dispose();
        bl.setVisible(true);
    }//GEN-LAST:event_blackjacklogoMouseClicked

    private void blackjacklogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blackjacklogoMouseEntered
        blackjacklogo.setLocation(70, 305);
    }//GEN-LAST:event_blackjacklogoMouseEntered

    private void blackjacklogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blackjacklogoMouseExited
        blackjacklogo.setLocation(70, 310);
    }//GEN-LAST:event_blackjacklogoMouseExited

    private void contMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contMouseEntered

    }//GEN-LAST:event_contMouseEntered

    private void contMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contMouseExited

    }//GEN-LAST:event_contMouseExited

    private void rompecabezaslogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rompecabezaslogoMouseClicked
        juegos.rompecabezas puzzle = new juegos.rompecabezas();
        this.dispose();
        puzzle.setVisible(true);
    }//GEN-LAST:event_rompecabezaslogoMouseClicked

    private void rompecabezaslogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rompecabezaslogoMouseEntered
        rompecabezaslogo.setLocation(550, 365);
    }//GEN-LAST:event_rompecabezaslogoMouseEntered

    private void rompecabezaslogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rompecabezaslogoMouseExited
        rompecabezaslogo.setLocation(550, 370);
    }//GEN-LAST:event_rompecabezaslogoMouseExited

    private void carreraslogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carreraslogoMouseClicked
        juegos.carreras car = new juegos.carreras();
        this.dispose();
        car.setVisible(true);
    }//GEN-LAST:event_carreraslogoMouseClicked

    private void carreraslogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carreraslogoMouseEntered
        carreraslogo.setLocation(310, 465);
    }//GEN-LAST:event_carreraslogoMouseEntered

    private void carreraslogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carreraslogoMouseExited
        carreraslogo.setLocation(310, 470);
    }//GEN-LAST:event_carreraslogoMouseExited

    private void blackjack1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blackjack1MouseEntered
      
    }//GEN-LAST:event_blackjack1MouseEntered

    /**
     * @param args the command line arguments
     */
    
   
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JLabel blackjack1;
    private javax.swing.JLabel blackjacklogo;
    private javax.swing.JLabel carreras;
    private javax.swing.JLabel carreraslogo;
    private javax.swing.JLabel cont;
    private javax.swing.JLabel cont2;
    private javax.swing.JLabel cont3;
    private javax.swing.JLabel cont4;
    private javax.swing.JLabel cont5;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel fondo4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo_gif;
    private javax.swing.JLabel marco;
    private javax.swing.JLabel rompecabezas;
    private javax.swing.JLabel rompecabezaslogo;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel serpientes;
    private javax.swing.JLabel serpienteslogo;
    private javax.swing.JLabel sopa;
    private javax.swing.JLabel sopalogo;
    // End of variables declaration//GEN-END:variables
}
