/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juegos;

import java.awt.Color;
import static java.awt.Color.pink;
import static java.awt.Color.white;
import java.awt.Toolkit;
import java.util.Arrays;
import java.util.Random;
import java.util.Scanner;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static juegos.blackjack.ap;
import static juegos.blackjack.baraja;
import static juegos.blackjack.cartaOculta;
import static juegos.blackjack.crupierCart;
import static juegos.blackjack.crupierTotal;
import static juegos.blackjack.din;
import static juegos.blackjack.i;
import static juegos.blackjack.jugadorCart;
import static juegos.blackjack.jugadorTotal;
import static juegos.blackjack.numBaraja;
import static juegos.blackjack.numCartas;
import static juegos.blackjack.palos;
import static juegos.blackjack.random;
import static juegos.blackjack.valores;
import static juegos.blackjack.values;
import static juegos.blackjack.vocul;

/**
 *
 * @author andre
 */
public class blackjack extends javax.swing.JFrame {

    /**
     * Creates new form a
     */
    public blackjack() {
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        flechas.setVisible(false);
        carta1.setVisible(false);
        carta2.setVisible(false);
        carta2.setVisible(false);
        carta3.setVisible(false);
        carta4.setVisible(false);
        carta5.setVisible(false);
        carta6.setVisible(false);
        carta7.setVisible(false);
        carta8.setVisible(false);
        carta9.setVisible(false);
        cartaBoton.setEnabled(false);
        pararBoton.setEnabled(false);
        fichav.setText("" + din);
        setIcon();
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("log.png")));
    }

    public String apuesta;
    public static Random random = new Random();
    public static Scanner leer = new Scanner(System.in);
    public static String[] palos = {"Corazones", "Diamantes", "Picas", "Tréboles"};
    public static String[] valores = {"As", "Dos", "Tres", "Cuatro", "Cinco", "Seis", "Siete", "Ocho", "Nueve", "Diez", "Jota", "Reina", "Rey"};
    public static int[] values = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10};
    public static int numBaraja = 1;
    public static int numCartas = numBaraja * 52;
    public static int[] baraja = new int[numCartas];
    public static int jugadorTotal = 0;
    public static int crupierTotal = 0;
    public static int jugadorCart = 0;
    public static int crupierCart = 0;
    public static int carta;
    public static int valor, vocul;
    public static int i = 1, ap, din = 1000;
    public String ocul, As;
    public boolean game;
    public static String cartaOculta = "";
    public Icon diamante = new ImageIcon(getClass().getResource("blackjackimg\\madia.png"));
    public Icon corazon = new ImageIcon(getClass().getResource("blackjackimg\\macor.png"));
    public Icon trebol = new ImageIcon(getClass().getResource("blackjackimg\\matrw.png"));
    public Icon pica = new ImageIcon(getClass().getResource("blackjackimg\\mapic.png"));
    public Icon espalda = new ImageIcon(getClass().getResource("blackjackimg\\espaldac.png"));
    public Icon logo = new ImageIcon(getClass().getResource("blackjackimg\\book.png"));
    public Icon lose = new ImageIcon(getClass().getResource("blackjackimg\\sad_cat.gif"));
    public Icon win = new ImageIcon(getClass().getResource("blackjackimg\\cool_cat.gif"));
    public Icon tie = new ImageIcon(getClass().getResource("blackjackimg\\surprised_cat.gif"));
    public Icon rules = new ImageIcon(getClass().getResource("blackjackimg\\mistery_cat.gif"));
    public Icon bet = new ImageIcon(getClass().getResource("blackjackimg\\sassy_cat.gif"));
    public Icon not = new ImageIcon(getClass().getResource("blackjackimg\\carefree_cat.gif"));
    public Icon gameover = new ImageIcon(getClass().getResource("blackjackimg\\dead_cat.gif"));
    public Icon normal = new ImageIcon(getClass().getResource("blackjackimg\\cat.gif"));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reglas = new javax.swing.JLabel();
        carta9v = new javax.swing.JLabel();
        carta9 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        carta8v = new javax.swing.JLabel();
        carta7v = new javax.swing.JLabel();
        carta6v = new javax.swing.JLabel();
        carta5v = new javax.swing.JLabel();
        carta4v = new javax.swing.JLabel();
        carta3v = new javax.swing.JLabel();
        carta2v = new javax.swing.JLabel();
        carta1v = new javax.swing.JLabel();
        carta5 = new javax.swing.JLabel();
        carta7 = new javax.swing.JLabel();
        carta1 = new javax.swing.JLabel();
        carta8 = new javax.swing.JLabel();
        carta6 = new javax.swing.JLabel();
        carta2 = new javax.swing.JLabel();
        carta4 = new javax.swing.JLabel();
        carta3 = new javax.swing.JLabel();
        diamantes = new javax.swing.JLabel();
        dia = new javax.swing.JPanel();
        lado2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        book = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        picas = new javax.swing.JLabel();
        pic = new javax.swing.JPanel();
        treboles = new javax.swing.JLabel();
        tre = new javax.swing.JPanel();
        flechas = new javax.swing.JLabel();
        fichav = new javax.swing.JLabel();
        corazones = new javax.swing.JLabel();
        lado1 = new javax.swing.JLabel();
        ficha = new javax.swing.JLabel();
        cor = new javax.swing.JPanel();
        totalCrupierlabel = new javax.swing.JLabel();
        crupier = new javax.swing.JLabel();
        jugadorTotallabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        crupier1 = new javax.swing.JLabel();
        pararBoton = new javax.swing.JButton();
        mar4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        repartirBoton = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cartaBoton = new javax.swing.JButton();
        volver = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ganancia = new javax.swing.JLabel();
        tab = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 1000), new java.awt.Dimension(0, 1000), new java.awt.Dimension(32767, 1000));
        jLabel8 = new javax.swing.JLabel();
        marco = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blackjack");

        jPanel1.setBackground(new java.awt.Color(46, 44, 48));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reglas.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        reglas.setForeground(new java.awt.Color(255, 255, 255));
        reglas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reglas.setText("Reglas");
        reglas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reglasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reglasMouseExited(evt);
            }
        });
        jPanel1.add(reglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, 80, -1));

        carta9v.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        carta9v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(carta9v, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 60, 20));

        carta9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/espaldac.png"))); // NOI18N
        jPanel1.add(carta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 370, 70, 90));

        jLabel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 75, 90));

        carta8v.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        carta8v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(carta8v, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 60, 20));

        carta7v.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        carta7v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(carta7v, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 60, 20));

        carta6v.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        carta6v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(carta6v, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 60, 20));

        carta5v.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        carta5v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(carta5v, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 60, 20));

        carta4v.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        carta4v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(carta4v, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 60, 20));

        carta3v.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        carta3v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(carta3v, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 60, 20));

        carta2v.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        carta2v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(carta2v, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 60, 20));

        carta1v.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        carta1v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(carta1v, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 60, 20));

        carta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/matrw.png"))); // NOI18N
        jPanel1.add(carta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 374, 70, -1));

        carta7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/espaldac.png"))); // NOI18N
        jPanel1.add(carta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 412, -1, -1));

        carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/madia.png"))); // NOI18N
        jPanel1.add(carta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 205, -1, -1));

        carta8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/espaldac.png"))); // NOI18N
        jPanel1.add(carta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 410, 70, 90));

        carta6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/macor.png"))); // NOI18N
        jPanel1.add(carta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 410, 70, 90));

        carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/mapic.png"))); // NOI18N
        jPanel1.add(carta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 175, -1, -1));

        carta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/espaldac.png"))); // NOI18N
        jPanel1.add(carta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 200, -1, 90));

        carta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/espaldac.png"))); // NOI18N
        jPanel1.add(carta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 175, -1, -1));

        diamantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/diamantes_1.png"))); // NOI18N
        diamantes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(diamantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, -1, 80));

        dia.setMaximumSize(new java.awt.Dimension(32767, 32764));

        javax.swing.GroupLayout diaLayout = new javax.swing.GroupLayout(dia);
        dia.setLayout(diaLayout);
        diaLayout.setHorizontalGroup(
            diaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        diaLayout.setVerticalGroup(
            diaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 62, 80));

        lado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/sep2.gif"))); // NOI18N
        jPanel1.add(lado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/ddmlrdo-d98a8784-66da-4ce3-a349-436e73764f23.gif"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/ddmlrdo-d98a8784-66da-4ce3-a349-436e73764f23.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, -1, -1));

        book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/book.png"))); // NOI18N
        book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookMouseExited(evt);
            }
        });
        jPanel1.add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/ddmlrdo-d98a8784-66da-4ce3-a349-436e73764f23.gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/ddmlrdo-d98a8784-66da-4ce3-a349-436e73764f23.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        picas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/picas.png"))); // NOI18N
        picas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(picas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, 80));

        pic.setMaximumSize(new java.awt.Dimension(32767, 32764));

        javax.swing.GroupLayout picLayout = new javax.swing.GroupLayout(pic);
        pic.setLayout(picLayout);
        picLayout.setHorizontalGroup(
            picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        picLayout.setVerticalGroup(
            picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 64, 80));

        treboles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/treboles.png"))); // NOI18N
        treboles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(treboles, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, 80));

        javax.swing.GroupLayout treLayout = new javax.swing.GroupLayout(tre);
        tre.setLayout(treLayout);
        treLayout.setHorizontalGroup(
            treLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        treLayout.setVerticalGroup(
            treLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(tre, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 80, 80));

        flechas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        flechas.setForeground(new java.awt.Color(255, 255, 255));
        flechas.setText("<<--------");
        jPanel1.add(flechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1012, 630, 80, -1));

        fichav.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        fichav.setForeground(new java.awt.Color(255, 255, 255));
        fichav.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fichav.setText("0");
        jPanel1.add(fichav, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 530, 70, 20));

        corazones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/corazones.png"))); // NOI18N
        corazones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(corazones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 80));

        lado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/sep.gif"))); // NOI18N
        jPanel1.add(lado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        ficha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/ficha (1).png"))); // NOI18N
        jPanel1.add(ficha, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, 140, 140));

        javax.swing.GroupLayout corLayout = new javax.swing.GroupLayout(cor);
        cor.setLayout(corLayout);
        corLayout.setHorizontalGroup(
            corLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        corLayout.setVerticalGroup(
            corLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 70, 80));

        totalCrupierlabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalCrupierlabel.setForeground(new java.awt.Color(255, 255, 255));
        totalCrupierlabel.setText("Total:");
        jPanel1.add(totalCrupierlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 90, 50));

        crupier.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        crupier.setForeground(new java.awt.Color(255, 255, 255));
        crupier.setText("JUGADOR");
        jPanel1.add(crupier, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, -1, -1));

        jugadorTotallabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jugadorTotallabel.setForeground(new java.awt.Color(255, 255, 255));
        jugadorTotallabel.setText("Total:");
        jPanel1.add(jugadorTotallabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 90, 50));

        jLabel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 75, 90));

        crupier1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        crupier1.setForeground(new java.awt.Color(255, 255, 255));
        crupier1.setText("CRUPIER");
        jPanel1.add(crupier1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        pararBoton.setBackground(new java.awt.Color(204, 204, 255));
        pararBoton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pararBoton.setText("Parar");
        pararBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pararBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/stop.png"))); // NOI18N
        pararBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pararBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pararBotonMouseExited(evt);
            }
        });
        pararBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pararBotonActionPerformed(evt);
            }
        });
        jPanel1.add(pararBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 140, 50));

        mar4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(mar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 75, 92));

        jLabel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 75, 90));

        jLabel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 75, 92));

        jLabel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 370, 75, 90));

        repartirBoton.setBackground(new java.awt.Color(204, 204, 255));
        repartirBoton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        repartirBoton.setText("Repartir");
        repartirBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        repartirBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/dados.png"))); // NOI18N
        repartirBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                repartirBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                repartirBotonMouseExited(evt);
            }
        });
        repartirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repartirBotonActionPerformed(evt);
            }
        });
        jPanel1.add(repartirBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 140, 50));

        jLabel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 75, 90));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/pinkspark.gif"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 330, -1, -1));

        cartaBoton.setBackground(new java.awt.Color(204, 204, 255));
        cartaBoton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cartaBoton.setText("+ Carta");
        cartaBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartaBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/+carta.png"))); // NOI18N
        cartaBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cartaBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cartaBotonMouseExited(evt);
            }
        });
        cartaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaBotonActionPerformed(evt);
            }
        });
        jPanel1.add(cartaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 140, 50));

        volver.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("VOLVER");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMouseExited(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1038, 610, 60, -1));

        jLabel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 75, 92));

        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 75, 92));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/pinkspark.gif"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 240, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/pinkspark.gif"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 145, -1, -1));

        ganancia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ganancia.setForeground(new java.awt.Color(255, 255, 255));
        ganancia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ganancia.setText("Tu apuesta: $0");
        jPanel1.add(ganancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, 180, 40));

        tab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/tab4.png"))); // NOI18N
        jPanel1.add(tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, -310, 10, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/pinkyc.gif"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 605, -1, -1));
        jLabel8.getAccessibleContext().setAccessibleName("");

        marco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(141, 237, 230), new java.awt.Color(236, 203, 237), new java.awt.Color(204, 51, 255), new java.awt.Color(208, 229, 253)));
        jPanel1.add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 1107, 650));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/pinkspark.gif"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 145, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/pinkspark.gif"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/pinkspark.gif"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reglasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reglasMouseEntered

    }//GEN-LAST:event_reglasMouseEntered

    private void reglasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reglasMouseExited

    }//GEN-LAST:event_reglasMouseExited

    private void bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseClicked

        JOptionPane.showMessageDialog(null, " 1. El objetivo del juego es obtener una puntuación lo más cercana posible a 21, sin pasarse.\n"
                + "\n 2. Las cartas se valoran de la siguiente manera: las cartas numéricas valen su valor nominal, \n"
                + "las cartas J, Q y K valen 10 puntos cada una, y el As puede valer 1 u 11 puntos, según le\n"
                + "convenga al jugador.\n"
                + "\n 3. El jugador juega contra el crupier, que también recibe dos cartas pero solo muestra una.\n"
                + "\n 4. El jugador puede plantarse (no tomar más cartas), o pedir más cartas hasta que se planta \n"
                + "o se pasa de 21 puntos (lo que se llama \"bust\").\n"
                + "\n 5. En caso de sobrepasar los 21 puntos quedará eliminado automáticamente.",
                "REGLAS - BLACKJACK", JOptionPane.INFORMATION_MESSAGE, rules);
    }//GEN-LAST:event_bookMouseClicked

    private void bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseEntered
        book.setLocation(1020, 25);
        reglas.setForeground(pink);
    }//GEN-LAST:event_bookMouseEntered

    private void bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseExited
        book.setLocation(1020, 30);
        reglas.setForeground(white);
    }//GEN-LAST:event_bookMouseExited

    private void pararBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pararBotonActionPerformed
        if (jugadorTotal <= 21 && jugadorTotal > crupierTotal) {

            JOptionPane.showMessageDialog(null, "Has ganado!", "", JOptionPane.INFORMATION_MESSAGE, win);
            JOptionPane.showMessageDialog(null, "La carta oculta del crupier era: \n" + cartaOculta, "Blackjack", JOptionPane.INFORMATION_MESSAGE, bet);
            if (ocul == "Corazones") {
                carta2.setIcon(corazon);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            } else if (ocul == "Diamantes") {
                carta2.setIcon(diamante);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            } else if (ocul == "Picas") {
                carta2.setIcon(pica);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            } else if (ocul == "Tréboles") {
                carta2.setIcon(trebol);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            }

            if (jugadorTotal == 21) {
                ap = ap * 2;
            }

            ganancia.setText("Has ganado: $" + ap);
            din = din + ap;
            fichav.setText("" + din);
            totalCrupierlabel.setText("Total: " + crupierTotal);
            cartaBoton.setEnabled(false);
            pararBoton.setEnabled(false);
            repartirBoton.setEnabled(true);
        } else if (crupierTotal <= 21 && crupierTotal > jugadorTotal) {
//            JOptionPane.showMessageDialog(null, "Ha ganado el crupier");
            JOptionPane.showMessageDialog(null, "Ha ganado el crupier", "", JOptionPane.INFORMATION_MESSAGE, lose);
            JOptionPane.showMessageDialog(null, "La carta oculta del crupier era: \n" + cartaOculta, "", JOptionPane.INFORMATION_MESSAGE, bet);
            if (ocul == "Corazones") {
                carta2.setIcon(corazon);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            } else if (ocul == "Diamantes") {
                carta2.setIcon(diamante);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            } else if (ocul == "Picas") {
                carta2.setIcon(pica);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            } else if (ocul == "Tréboles") {
                carta2.setIcon(trebol);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            }

            ganancia.setText("Has perdido: $" + ap);
            din = din - ap;
            fichav.setText("" + din);
            totalCrupierlabel.setText("Total: " + crupierTotal);
            cartaBoton.setEnabled(false);
            pararBoton.setEnabled(false);
            repartirBoton.setEnabled(true);
        } else if (crupierTotal == jugadorTotal) {
            JOptionPane.showMessageDialog(null, "Ha habido un empate!", "", JOptionPane.INFORMATION_MESSAGE, tie);
            JOptionPane.showMessageDialog(null, "La carta oculta del crupier era: \n" + cartaOculta, "Blackjack", JOptionPane.INFORMATION_MESSAGE, bet);
            totalCrupierlabel.setText("Total: " + crupierTotal);
            if (ocul == "Corazones") {
                carta2.setIcon(corazon);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            } else if (ocul == "Diamantes") {
                carta2.setIcon(diamante);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            } else if (ocul == "Picas") {
                carta2.setIcon(pica);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            } else if (ocul == "Tréboles") {
                carta2.setIcon(trebol);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            }
            if (jugadorTotal == 21) {
                ap = ap * 2;
            }
            ganancia.setText("Has ganado: $" + ap);
            din = din + ap;
            fichav.setText("" + din);
            cartaBoton.setEnabled(false);
            pararBoton.setEnabled(false);
            repartirBoton.setEnabled(true);
        }

        cartaBoton.setEnabled(false);
        pararBoton.setEnabled(false);

        if (din <= 0) {
            JOptionPane.showMessageDialog(null, "Juego terminado, no te quedan fondos para seguir apostando", "", JOptionPane.INFORMATION_MESSAGE, gameover);
            repartirBoton.setEnabled(false);
        }
    }//GEN-LAST:event_pararBotonActionPerformed
    public void limpiar() {
        numBaraja = 1;
        numCartas = numBaraja * 52;
        baraja = new int[numCartas];
        jugadorTotal = 0;
        crupierTotal = 0;
        jugadorCart = 0;
        crupierCart = 0;
        carta1v.setText("");
        carta2v.setText("");
        carta3v.setText("");
        carta4v.setText("");
        carta5v.setText("");
        carta6v.setText("");
        carta7v.setText("");
        carta8v.setText("");
        carta9v.setText("");
        totalCrupierlabel.setText("Total: 0");
        jugadorTotallabel.setText("Total: 0");
        i = 1;
        cartaOculta = "";
        carta1.setVisible(false);
        carta2.setVisible(false);
        carta2.setVisible(false);
        carta3.setVisible(false);
        carta4.setVisible(false);
        carta5.setVisible(false);
        carta6.setVisible(false);
        carta7.setVisible(false);
        carta8.setVisible(false);
        carta9.setVisible(false);
        cartaBoton.setEnabled(false);
        pararBoton.setEnabled(false);
    }

    public void repartir() {
        apuesta = (String) JOptionPane.showInputDialog(null, "Cuánto desea apostar? ", "", JOptionPane.INFORMATION_MESSAGE, bet, null, "");
        ap = (Integer.parseInt(apuesta));
        while (ap <= 0) {
            apuesta = (String) JOptionPane.showInputDialog(null, "Ingrese un número válido:", "", JOptionPane.INFORMATION_MESSAGE, not, null, "");
            ap = (Integer.parseInt(apuesta));
        }
        while (ap > din) {
            apuesta = (String) JOptionPane.showInputDialog(null, "Fondos insuficientes!, intente un valor más bajo:", "", JOptionPane.INFORMATION_MESSAGE, not, null, "");
            ap = (Integer.parseInt(apuesta));
        }

        fichav.setText("" + din);
        ganancia.setText("Tu apuesta: $" + ap);

        cartaBoton.setEnabled(true);
        pararBoton.setEnabled(true);

        for (int i = 0; i < numCartas; i++) {
            baraja[i] = i;
        }
        for (int i = numCartas - 1; i > 0; i--) {
            int j = random.nextInt(i + 1);
            int temp = baraja[j];
            baraja[j] = temp;
        }

        while (jugadorCart < 2 || crupierCart < 2) {
            int carta = baraja[0];
            int c = random.nextInt(13 - 1);
            int p = random.nextInt(4 - 1);
            int valor = values[c];

            String pal = "";
            if (jugadorCart < 2) {
                JOptionPane.showMessageDialog(null, "Toma una carta: \n" + valores[c] + " de " + palos[p], "", JOptionPane.INFORMATION_MESSAGE, normal);
                jugadorCart = jugadorCart + 2;
                jugadorTotallabel.setText("Total: " + jugadorTotal);
                carta = baraja[0];
                valor = values[c];
                if (valores[c] == "As" && (jugadorTotal + 11) <= 21) {
                    valor = 11;
                }
                jugadorTotal = jugadorTotal + valor;
                pal = palos[p];
                if (pal == "Corazones") {
                    carta5.setIcon(corazon);
                    carta5.setVisible(true);
                    carta5v.setText("" + valor);
                } else if (pal == "Diamantes") {
                    carta5.setIcon(diamante);
                    carta5.setVisible(true);
                    carta5v.setText("" + valor);
                } else if (pal == "Picas") {
                    carta5.setIcon(pica);
                    carta5.setVisible(true);
                    carta5v.setText("" + valor);
                } else if (pal == "Tréboles") {
                    carta5.setIcon(trebol);
                    carta5.setVisible(true);
                    carta5v.setText("" + valor);
                }

                jugadorCart++;
                c = random.nextInt(13 - 1);
                p = random.nextInt(4 - 1);
                JOptionPane.showMessageDialog(null, "Toma una carta: \n" + valores[c] + " de " + palos[p], "", JOptionPane.INFORMATION_MESSAGE, normal);
                baraja = Arrays.copyOfRange(baraja, 1, baraja.length);
                carta = baraja[0];
                valor = values[c];
                if (valores[c] == "As" && (jugadorTotal + 11) <= 21) {
                    valor = 11;
                }
                jugadorTotal = jugadorTotal + valor;
                pal = palos[p];
                if (pal == "Corazones") {
                    carta6.setIcon(corazon);
                    carta6.setVisible(true);
                    carta6v.setText("" + valor);
                } else if (pal == "Diamantes") {
                    carta6.setIcon(diamante);
                    carta6.setVisible(true);
                    carta6v.setText("" + valor);
                } else if (pal == "Picas") {
                    carta6.setIcon(pica);
                    carta6.setVisible(true);
                    carta6v.setText("" + valor);
                } else if (pal == "Tréboles") {
                    carta6.setIcon(trebol);
                    carta6.setVisible(true);
                    carta6v.setText("" + valor);
                }
                jugadorTotallabel.setText("Total: " + jugadorTotal);
            } else {

                if (crupierCart < 2) {
                    c = random.nextInt(13 - 1);
                    p = random.nextInt(4 - 1);
                    carta = baraja[0];
                    valor = values[c];
                    pal = palos[p];
                    crupierCart = crupierCart + 2;
                    totalCrupierlabel.setText("Total: " + crupierTotal);
                    JOptionPane.showMessageDialog(null, "El crupier toma una carta boca arriba: \n" + valores[c] + " de " + palos[p], "", JOptionPane.INFORMATION_MESSAGE, normal);
                    totalCrupierlabel.setText("Total: " + crupierTotal);
                    carta = baraja[0];
                    valor = values[c];
                    if (valores[c] == "As" && (crupierTotal + 11) <= 21) {
                        valor = 11;
                    }
                    crupierTotal = crupierTotal + valor;
                    totalCrupierlabel.setText("Total: " + crupierTotal);
                    if (pal == "Corazones") {
                        carta1.setIcon(corazon);
                        carta1.setVisible(true);
                        carta1v.setText("" + valor);
                    } else if (pal == "Diamantes") {
                        carta1.setIcon(diamante);
                        carta1.setVisible(true);
                        carta1v.setText("" + valor);
                    } else if (pal == "Picas") {
                        carta1.setIcon(pica);
                        carta1.setVisible(true);
                        carta1v.setText("" + valor);
                    } else if (pal == "Tréboles") {
                        carta1.setIcon(trebol);
                        carta1.setVisible(true);
                        carta1v.setText("" + valor);
                    }
                    crupierCart++;
                    baraja = Arrays.copyOfRange(baraja, 1, baraja.length);
                    JOptionPane.showMessageDialog(null, "El crupier toma una carta boca abajo", "", JOptionPane.INFORMATION_MESSAGE, normal);
                    c = random.nextInt(13 - 1);
                    p = random.nextInt(4 - 1);
                    carta2.setIcon(espalda);
                    carta2.setVisible(true);
                    cartaOculta = (valores[c] + " de " + palos[p]);
                    ocul = palos[p];
                    vocul = values[c];
                    if (valores[c] == "As" && (jugadorTotal + 11) <= 21) {
                        vocul = 11;
                    }
                    crupierTotal = crupierTotal + vocul;
                } else {

                }
            }
            baraja = Arrays.copyOfRange(baraja, 1, baraja.length);
        }

        cartaBoton.setVisible(true);
        pararBoton.setVisible(true);
        repartirBoton.setEnabled(false);
    }
    private void repartirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repartirBotonActionPerformed
        limpiar();
        repartir();
    }//GEN-LAST:event_repartirBotonActionPerformed

    private void cartaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaBotonActionPerformed
        int c = random.nextInt(13 - 1);
        int p = random.nextInt(4 - 1);
        carta = baraja[0];
        valor = values[c];
        jugadorTotal = jugadorTotal + valor;

        if (jugadorTotal < 21 && i <= 1) {

            JOptionPane.showMessageDialog(null, "Toma una carta: \n" + valores[c] + " de " + palos[p], "", JOptionPane.INFORMATION_MESSAGE, normal);
            jugadorCart++;
            baraja = Arrays.copyOfRange(baraja, 1, baraja.length);
            jugadorTotallabel.setText("Total: " + jugadorTotal);
            baraja = Arrays.copyOfRange(baraja, 1, baraja.length);
            int carta3 = baraja[0];
            int valor3 = values[c];
            if (valores[c] == "As" && (jugadorTotal + 11) <= 21) {
                valor3 = 11;
            }
            String pal = "";
            pal = palos[p];
            if (pal == "Corazones") {
                carta7.setIcon(corazon);
                carta7.setVisible(true);
                carta7v.setText("" + valor3);
            } else if (pal == "Diamantes") {
                carta7.setIcon(diamante);
                carta7.setVisible(true);
                carta7v.setText("" + valor3);
            } else if (pal == "Picas") {
                carta7.setIcon(pica);
                carta7.setVisible(true);
                carta7v.setText("" + valor3);
            } else if (pal == "Tréboles") {
                carta7.setIcon(trebol);
                carta7.setVisible(true);
                carta7v.setText("" + valor3);

            }
            i = i + 1;
        } else if (jugadorTotal < 21 && i > 1) {
            c = random.nextInt(13 - 1);
            p = random.nextInt(4 - 1);
            jugadorCart++;

            JOptionPane.showMessageDialog(null, "Toma una carta: \n" + valores[c] + " de " + palos[p], "", JOptionPane.INFORMATION_MESSAGE, bet);

            baraja = Arrays.copyOfRange(baraja, 1, baraja.length);
            jugadorTotallabel.setText("Total: " + jugadorTotal);
            int carta4 = baraja[0];
            int valor4 = values[c];
            if (valores[c] == "As" && (jugadorTotal + 11) <= 21) {
                valor4 = 11;
            }
            String pal1 = "";
            pal1 = palos[p];
            if (pal1 == "Corazones") {
                carta8.setIcon(corazon);
                carta8.setVisible(true);
                carta8v.setText("" + valor4);
            } else if (pal1 == "Diamantes") {
                carta8.setIcon(diamante);
                carta8.setVisible(true);
                carta8v.setText("" + valor4);
            } else if (pal1 == "Picas") {
                carta8.setIcon(pica);
                carta8.setVisible(true);
                carta8v.setText("" + valor4);
            } else if (pal1 == "Tréboles") {
                carta8.setIcon(trebol);
                carta8.setVisible(true);
                carta8v.setText("" + valor4);
            }

        } else if (jugadorTotal > 21 && crupierTotal <= 21) {
            JOptionPane.showMessageDialog(null, "Toma una carta: \n" + valores[c] + " de " + palos[p], "", JOptionPane.INFORMATION_MESSAGE, normal);
            baraja = Arrays.copyOfRange(baraja, 1, baraja.length);
            jugadorTotallabel.setText("Total: " + jugadorTotal);
            baraja = Arrays.copyOfRange(baraja, 1, baraja.length);
            JOptionPane.showMessageDialog(null, "Te has pasado! gana el crupier", "", JOptionPane.INFORMATION_MESSAGE, lose);
            JOptionPane.showMessageDialog(null, "La carta oculta del crupier era: \n" + cartaOculta, "", JOptionPane.INFORMATION_MESSAGE, bet);
            totalCrupierlabel.setText("Total: " + crupierTotal);

            int carta = baraja[0];
            int valor = values[c];
            String pal = "";
            pal = palos[p];
            if (jugadorCart <= 3) {
                if (pal == "Corazones") {
                    carta7.setIcon(corazon);
                    carta7.setVisible(true);
                    carta7v.setText("" + valor);
                } else if (pal == "Diamantes") {
                    carta7.setIcon(diamante);
                    carta7.setVisible(true);
                    carta7v.setText("" + valor);
                } else if (pal == "Picas") {
                    carta7.setIcon(pica);
                    carta7.setVisible(true);
                    carta7v.setText("" + valor);
                } else if (pal == "Tréboles") {
                    carta7.setIcon(trebol);
                    carta7.setVisible(true);
                    carta7v.setText("" + valor);

                }
            } else if (jugadorCart >= 4) {
                if (pal == "Corazones") {
                    carta8.setIcon(corazon);
                    carta8.setVisible(true);
                    carta8v.setText("" + valor);
                } else if (pal == "Diamantes") {
                    carta8.setIcon(diamante);
                    carta8.setVisible(true);
                    carta8v.setText("" + valor);
                } else if (pal == "Picas") {
                    carta8.setIcon(pica);
                    carta8.setVisible(true);
                    carta8v.setText("" + valor);
                } else if (pal == "Tréboles") {
                    carta8.setIcon(trebol);
                    carta8.setVisible(true);
                    carta8v.setText("" + valor);

                }
            } else if (jugadorCart > 4) {
                if (pal == "Corazones") {
                    carta9.setIcon(corazon);
                    carta9.setVisible(true);
                    carta9v.setText("" + valor);
                } else if (pal == "Diamantes") {
                    carta9.setIcon(diamante);
                    carta9.setVisible(true);
                    carta9v.setText("" + valor);
                } else if (pal == "Picas") {
                    carta9.setIcon(pica);
                    carta9.setVisible(true);
                    carta9v.setText("" + valor);
                } else if (pal == "Tréboles") {
                    carta9.setIcon(trebol);
                    carta9.setVisible(true);
                    carta9v.setText("" + valor);

                }
            }

            if (ocul == "Corazones") {
                carta2.setIcon(corazon);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            } else if (ocul == "Diamantes") {
                carta2.setIcon(diamante);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            } else if (ocul == "Picas") {
                carta2.setIcon(pica);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            } else if (ocul == "Tréboles") {
                carta2.setIcon(trebol);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            }

            ganancia.setText("Has perdido: $" + ap);
            din = din - ap;
            fichav.setText("" + din);
            cartaBoton.setEnabled(false);
            pararBoton.setEnabled(false);
            repartirBoton.setEnabled(true);
        } else if (jugadorTotal <= 21 && crupierTotal > 21) {
            JOptionPane.showMessageDialog(null, "El crupier se ha pasado, ganas el juego", "", JOptionPane.INFORMATION_MESSAGE, win);
            JOptionPane.showMessageDialog(null, "La carta oculta del crupier era: \n" + cartaOculta, "", JOptionPane.INFORMATION_MESSAGE, bet);

            totalCrupierlabel.setText("Total: " + crupierTotal);
            if (ocul == "Corazones") {
                carta2.setIcon(corazon);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            } else if (ocul == "Diamantes") {
                carta2.setIcon(diamante);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            } else if (ocul == "Picas") {
                carta2.setIcon(pica);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            } else if (ocul == "Tréboles") {
                carta2.setIcon(trebol);
                carta2.setVisible(true);
                carta2v.setText("" + vocul);
            }
            if (jugadorTotal == 21) {
                ap = ap * 2;
            }
            cartaBoton.setEnabled(false);
            pararBoton.setEnabled(false);
            repartirBoton.setEnabled(true);
            ganancia.setText("Has ganado: " + ap);
            din = din + ap;
            fichav.setText("" + din);
        }

        if (din <= 0) {
            JOptionPane.showMessageDialog(null, "Juego terminado, no te quedan fondos para seguir apostando", "", JOptionPane.INFORMATION_MESSAGE, gameover);
            repartirBoton.setEnabled(false);
        }
    }//GEN-LAST:event_cartaBotonActionPerformed

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        limpiar();
        din = 1000;
        main.Menu menu = new main.Menu();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_volverMouseClicked

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        flechas.setVisible(true);
        volver.setForeground(pink);
        flechas.setForeground(pink);
    }//GEN-LAST:event_volverMouseEntered

    private void volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseExited
        flechas.setVisible(false);
        volver.setForeground(white);
        flechas.setForeground(white);
    }//GEN-LAST:event_volverMouseExited

    private void repartirBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repartirBotonMouseEntered
        repartirBoton.setBackground(new Color(153, 153, 255));
    }//GEN-LAST:event_repartirBotonMouseEntered

    private void repartirBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repartirBotonMouseExited
        repartirBoton.setBackground(new Color(204, 204, 255));
    }//GEN-LAST:event_repartirBotonMouseExited

    private void cartaBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaBotonMouseEntered
        cartaBoton.setBackground(new Color(153, 153, 255));
    }//GEN-LAST:event_cartaBotonMouseEntered

    private void pararBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pararBotonMouseEntered
        pararBoton.setBackground(new Color(153, 153, 255));
    }//GEN-LAST:event_pararBotonMouseEntered

    private void cartaBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaBotonMouseExited
        cartaBoton.setBackground(new Color(204, 204, 255));
    }//GEN-LAST:event_cartaBotonMouseExited

    private void pararBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pararBotonMouseExited
        pararBoton.setBackground(new Color(204, 204, 255));
    }//GEN-LAST:event_pararBotonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(blackjack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(blackjack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(blackjack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(blackjack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new blackjack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel book;
    private javax.swing.JLabel carta1;
    private javax.swing.JLabel carta1v;
    private javax.swing.JLabel carta2;
    private javax.swing.JLabel carta2v;
    private javax.swing.JLabel carta3;
    private javax.swing.JLabel carta3v;
    private javax.swing.JLabel carta4;
    private javax.swing.JLabel carta4v;
    private javax.swing.JLabel carta5;
    private javax.swing.JLabel carta5v;
    private javax.swing.JLabel carta6;
    private javax.swing.JLabel carta6v;
    private javax.swing.JLabel carta7;
    private javax.swing.JLabel carta7v;
    private javax.swing.JLabel carta8;
    private javax.swing.JLabel carta8v;
    private javax.swing.JLabel carta9;
    private javax.swing.JLabel carta9v;
    private javax.swing.JButton cartaBoton;
    private javax.swing.JPanel cor;
    private javax.swing.JLabel corazones;
    private javax.swing.JLabel crupier;
    private javax.swing.JLabel crupier1;
    private javax.swing.JPanel dia;
    private javax.swing.JLabel diamantes;
    private javax.swing.JLabel ficha;
    private javax.swing.JLabel fichav;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel flechas;
    private javax.swing.JLabel ganancia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jugadorTotallabel;
    private javax.swing.JLabel lado1;
    private javax.swing.JLabel lado2;
    private javax.swing.JLabel mar4;
    private javax.swing.JLabel marco;
    private javax.swing.JButton pararBoton;
    private javax.swing.JPanel pic;
    private javax.swing.JLabel picas;
    private javax.swing.JLabel reglas;
    private javax.swing.JButton repartirBoton;
    private javax.swing.JLabel tab;
    private javax.swing.JLabel totalCrupierlabel;
    private javax.swing.JPanel tre;
    private javax.swing.JLabel treboles;
    private javax.swing.JLabel volver;
    // End of variables declaration//GEN-END:variables
}
