/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juegos;

import java.awt.Color;
import static java.awt.Color.pink;
import static java.awt.Color.white;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.Timer;

/**
 *
 * @author andre
 */
public class carreras extends javax.swing.JFrame {

    /**
     * Creates new form carreras
     */
    private final int MAX_POSICION = 590;

    Hilo hilo;

    // Hilos de los carros
    private CarroThread t1, t2, t3;

    // Estado de la carrera
    private boolean carreraActiva = false;

    // Orden de llegada
    private final List<String> ordenLlegada = new ArrayList<>();

    public carreras() {
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);

        hilo = new Hilo(this);
        hilo.start();

        c1.setText(nombre1);
        c2.setText(nombre2);
        c3.setText(nombre3);
        tabla.setEditable(false);
        setIcon();
        Carro1.setName(nombre1);
        Carro2.setName(nombre2);
        Carro3.setName(nombre3);

    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("log.png")));
    }

    public void moverFondo() {
        fondo.setLocation(fondo.getX() - 2, fondo.getY());
    }

    public Icon normal = new ImageIcon(getClass().getResource("blackjackimg\\cat.gif"));
    public Icon win = new ImageIcon(getClass().getResource("sopaimg\\happy_cat.gif"));
    public String nombre1 = "Carro 1", nombre2 = "Carro 2", nombre3 = "Carro 3";
    public Icon carrito = new ImageIcon(getClass().getResource("/carrerasimg/cargif_2.gif"));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        marco = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pista = new javax.swing.JPanel();
        Carro1 = new javax.swing.JLabel();
        Carro2 = new javax.swing.JLabel();
        Carro3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();
        line = new javax.swing.JPanel();
        line1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        marco1 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(1000, 0), new java.awt.Dimension(1000, 0), new java.awt.Dimension(1000, 32767));
        Reiniciar = new javax.swing.JButton();
        pasto12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        arbol5 = new javax.swing.JLabel();
        arbol9 = new javax.swing.JLabel();
        pasto8 = new javax.swing.JLabel();
        pasto11 = new javax.swing.JLabel();
        pasto13 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        gente = new javax.swing.JLabel();
        arbol = new javax.swing.JLabel();
        bandera = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(32767, 100));
        arbol1 = new javax.swing.JLabel();
        arbol3 = new javax.swing.JLabel();
        arbol4 = new javax.swing.JLabel();
        bomba1 = new javax.swing.JLabel();
        paddock = new javax.swing.JLabel();
        pasto = new javax.swing.JLabel();
        pasto4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bomba = new javax.swing.JLabel();
        arbol6 = new javax.swing.JLabel();
        arbol7 = new javax.swing.JLabel();
        pasto3 = new javax.swing.JLabel();
        pasto9 = new javax.swing.JLabel();
        arbol8 = new javax.swing.JLabel();
        pasto10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        volver = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        flechas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTextArea();
        marco2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        marco3 = new javax.swing.JLabel();

        marco.setBackground(new java.awt.Color(255, 204, 255));
        marco.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        marco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carreras");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(46, 44, 48));
        jPanel1.setMinimumSize(new java.awt.Dimension(1130, 690));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/75.gif"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, 10));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/carree.gif"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 610, 320, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/carree.gif"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, 280, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/carree.gif"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, -1, 20));

        jPanel2.setBackground(new java.awt.Color(46, 44, 48));

        pista.setBackground(new java.awt.Color(102, 102, 102));
        pista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pistaKeyPressed(evt);
            }
        });
        pista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Carro1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        Carro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/carro (2).png"))); // NOI18N
        Carro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro1MouseClicked(evt);
            }
        });
        pista.add(Carro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 250, 60));

        Carro2.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        Carro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/carro (2) (1).png"))); // NOI18N
        Carro2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro2MouseClicked(evt);
            }
        });
        pista.add(Carro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 260, 50));

        Carro3.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        Carro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/carro (2) (2).png"))); // NOI18N
        Carro3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro3MouseClicked(evt);
            }
        });
        pista.add(Carro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 280, 50));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(242, 242, 242), new java.awt.Color(51, 51, 51), new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pista.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 0, 40, 30));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(242, 242, 242), new java.awt.Color(51, 51, 51), new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        pista.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, 30));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(242, 242, 242), new java.awt.Color(51, 51, 51), new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pista.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(242, 242, 242), new java.awt.Color(51, 51, 51), new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pista.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(242, 242, 242), new java.awt.Color(51, 51, 51), new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pista.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, -1, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(242, 242, 242), new java.awt.Color(51, 51, 51), new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pista.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(242, 242, 242), new java.awt.Color(51, 51, 51), new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pista.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(242, 242, 242), new java.awt.Color(51, 51, 51), new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pista.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, -1, -1));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(242, 242, 242), new java.awt.Color(51, 51, 51), new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pista.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, -1, -1));

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(242, 242, 242), new java.awt.Color(51, 51, 51), new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pista.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, -1, -1));

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(242, 242, 242), new java.awt.Color(51, 51, 51), new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pista.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, -1, -1));

        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(242, 242, 242), new java.awt.Color(51, 51, 51), new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pista.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, -1, -1));

        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(242, 242, 242), new java.awt.Color(51, 51, 51), new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pista.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, -1, -1));

        jPanel16.setBackground(new java.awt.Color(0, 0, 0));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(242, 242, 242), new java.awt.Color(51, 51, 51), new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pista.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/fondopista.png"))); // NOI18N
        pista.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 2000, 330));

        line.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        line.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pista.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 10));

        line1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        line1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pista.add(line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 770, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("- - - - - - - - - - - - - - - - - - - - - -");
        pista.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        marco1.setBackground(new java.awt.Color(255, 204, 255));
        marco1.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        marco1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pista.add(marco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -120, 765, 515));

        jPanel17.setBackground(new java.awt.Color(0, 153, 0));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 770, 30));

        Reiniciar.setBackground(new java.awt.Color(204, 204, 255));
        Reiniciar.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        Reiniciar.setText("INICIAR CARRERA");
        Reiniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Reiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReiniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReiniciarMouseExited(evt);
            }
        });
        Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarActionPerformed(evt);
            }
        });
        Reiniciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ReiniciarKeyPressed(evt);
            }
        });
        jPanel17.add(Reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 135, 50));

        pasto12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/grass.png"))); // NOI18N
        jPanel17.add(pasto12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/icons8-garage-64.png"))); // NOI18N
        jPanel17.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/icons8-garage-64.png"))); // NOI18N
        jPanel17.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        arbol5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/arbol (1).png"))); // NOI18N
        jPanel17.add(arbol5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        arbol9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/arbol (1).png"))); // NOI18N
        jPanel17.add(arbol9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        pasto8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/grass.png"))); // NOI18N
        jPanel17.add(pasto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        pasto11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/grass.png"))); // NOI18N
        jPanel17.add(pasto11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 135, -1, -1));

        pasto13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/grass.png"))); // NOI18N
        jPanel17.add(pasto13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, -1, -1));

        jPanel18.setBackground(new java.awt.Color(0, 153, 0));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/_con.png"))); // NOI18N
        jPanel18.add(gente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 110, -1));

        arbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/arbol (1).png"))); // NOI18N
        jPanel18.add(arbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        bandera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/bandera.png"))); // NOI18N
        jPanel18.add(bandera, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, -1, -1));
        jPanel18.add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 770, 10));

        arbol1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/d.png"))); // NOI18N
        jPanel18.add(arbol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 110, -1));

        arbol3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/mn.png"))); // NOI18N
        jPanel18.add(arbol3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        arbol4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/arbol (1).png"))); // NOI18N
        jPanel18.add(arbol4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        bomba1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/neu.png"))); // NOI18N
        jPanel18.add(bomba1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 90, -1));

        paddock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/sema.png"))); // NOI18N
        paddock.setLabelFor(paddock);
        paddock.setAutoscrolls(true);
        jPanel18.add(paddock, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        pasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/grass.png"))); // NOI18N
        jPanel18.add(pasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        pasto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/grass.png"))); // NOI18N
        jPanel18.add(pasto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/mn.png"))); // NOI18N
        jPanel18.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        bomba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/neu.png"))); // NOI18N
        jPanel18.add(bomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 90, 100));

        arbol6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/arbol (1).png"))); // NOI18N
        jPanel18.add(arbol6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        arbol7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/arbol (1).png"))); // NOI18N
        jPanel18.add(arbol7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        pasto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/grass.png"))); // NOI18N
        jPanel18.add(pasto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        pasto9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/grass.png"))); // NOI18N
        jPanel18.add(pasto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        arbol8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/arbol (1).png"))); // NOI18N
        jPanel18.add(arbol8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        pasto10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/grass.png"))); // NOI18N
        jPanel18.add(pasto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pista, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pista, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(335, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 373, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 770, 520));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Posiciones");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 240, -1));

        volver.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("VOLVER");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMouseExited(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1038, 610, 60, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/pinkyc.gif"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 605, -1, -1));

        flechas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        flechas.setForeground(new java.awt.Color(255, 255, 255));
        flechas.setText("<<--------");
        jPanel1.add(flechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1012, 630, 80, -1));

        tabla.setEditable(false);
        tabla.setBackground(new java.awt.Color(224, 224, 255));
        tabla.setColumns(20);
        tabla.setFont(new java.awt.Font("Segoe UI Historic", 2, 14)); // NOI18N
        tabla.setLineWrap(true);
        tabla.setRows(5);
        tabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabla.setCaretColor(new java.awt.Color(242, 242, 242));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 250, 110));

        marco2.setBackground(new java.awt.Color(255, 204, 255));
        marco2.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        marco2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(marco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 250, 110));

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CARRERAS");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Historic", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jugadores");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, 250, -1));

        c3.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        c3.setForeground(new java.awt.Color(255, 255, 255));
        c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/carr3.png"))); // NOI18N
        c3.setText("Carro 3");
        c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c3MouseExited(evt);
            }
        });
        jPanel1.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 530, 190, 90));

        c1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/carr.png"))); // NOI18N
        c1.setText("Carro 1");
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c1MouseExited(evt);
            }
        });
        jPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 360, 190, 90));

        c2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 255, 255));
        c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/carr2.png"))); // NOI18N
        c2.setText("Carro 2");
        c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c2MouseExited(evt);
            }
        });
        jPanel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, 190, 90));

        jLabel13.setFont(new java.awt.Font("Segoe UI Historic", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tabla de");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 140, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/75.gif"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/crystal-line.gif"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 190, 50, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/crystal-line.gif"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/crystal-line.gif"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrerasimg/asteroid.gif"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 80, -1, -1));

        marco3.setBackground(new java.awt.Color(255, 204, 255));
        marco3.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        marco3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        marco3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                marco3MouseEntered(evt);
            }
        });
        jPanel1.add(marco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 1100, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pistaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pistaKeyPressed

    }//GEN-LAST:event_pistaKeyPressed

    private void ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarActionPerformed

        iniciarCarrera();

    }//GEN-LAST:event_ReiniciarActionPerformed

    private void ReiniciarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ReiniciarKeyPressed
        iniciarCarrera();

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            iniciarCarrera();
        }
    }//GEN-LAST:event_ReiniciarKeyPressed

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        main.Menu menu = new main.Menu();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_volverMouseClicked

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        flechas.setVisible(true);
        volver.setForeground(pink);
        flechas.setForeground(pink);
    }//GEN-LAST:event_volverMouseEntered

    private void volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseExited
        flechas.setVisible(false);
        volver.setForeground(white);
    }//GEN-LAST:event_volverMouseExited

    private void Carro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro1MouseClicked
        nombre1 = (String) JOptionPane.showInputDialog(
                null,
                "Ingrese un nombre: ",
                "",
                JOptionPane.INFORMATION_MESSAGE,
                normal,
                null,
                ""
        );

        if (nombre1 == null || nombre1.trim().isEmpty()) {
            nombre1 = "Carro 1";
        }

        while (nombre1.equals(nombre2) || nombre1.equals(nombre3)) {
            nombre1 = (String) JOptionPane.showInputDialog(
                    null,
                    "Ya hay un carro con ese nombre, ingrese uno diferente:",
                    "",
                    JOptionPane.INFORMATION_MESSAGE,
                    normal,
                    null,
                    ""
            );

            if (nombre1 == null || nombre1.trim().isEmpty()) {
                nombre1 = "Carro 1";
                break;
            }
        }

        c1.setText(nombre1);
        Carro1.setName(nombre1);
    }//GEN-LAST:event_Carro1MouseClicked

    private void Carro2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro2MouseClicked
        nombre2 = (String) JOptionPane.showInputDialog(
                null,
                "Ingrese un nombre: ",
                "",
                JOptionPane.INFORMATION_MESSAGE,
                normal,
                null,
                ""
        );

        if (nombre2 == null || nombre2.trim().isEmpty()) {
            nombre2 = "Carro 2";
        }

        while (nombre2.equals(nombre1) || nombre2.equals(nombre3)) {
            nombre2 = (String) JOptionPane.showInputDialog(
                    null,
                    "Ya hay un carro con ese nombre, ingrese uno diferente:",
                    "",
                    JOptionPane.INFORMATION_MESSAGE,
                    normal,
                    null,
                    ""
            );

            if (nombre2 == null || nombre2.trim().isEmpty()) {
                nombre2 = "Carro 2";
                break;
            }
        }

        c2.setText(nombre2);
        Carro2.setName(nombre2);
    }//GEN-LAST:event_Carro2MouseClicked

    private void Carro3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro3MouseClicked
        nombre3 = (String) JOptionPane.showInputDialog(
                null,
                "Ingrese un nombre: ",
                "",
                JOptionPane.INFORMATION_MESSAGE,
                normal,
                null,
                ""
        );

        if (nombre3 == null || nombre3.trim().isEmpty()) {
            nombre3 = "Carro 3";
        }

        while (nombre3.equals(nombre1) || nombre3.equals(nombre2)) {
            nombre3 = (String) JOptionPane.showInputDialog(
                    null,
                    "Ya hay un carro con ese nombre, ingrese uno diferente:",
                    "",
                    JOptionPane.INFORMATION_MESSAGE,
                    normal,
                    null,
                    ""
            );

            if (nombre3 == null || nombre3.trim().isEmpty()) {
                nombre3 = "Carro 3";
                break;
            }
        }

        c3.setText(nombre3);
        Carro3.setName(nombre3);

    }//GEN-LAST:event_Carro3MouseClicked

    private void c1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseClicked
        nombre1 = (String) JOptionPane.showInputDialog(
                null,
                "Ingrese un nombre: ",
                "",
                JOptionPane.INFORMATION_MESSAGE,
                normal,
                null,
                ""
        );

        if (nombre1 == null || nombre1.trim().isEmpty()) {
            nombre1 = "Carro 1";
        }

        while (nombre1.equals(nombre2) || nombre1.equals(nombre3)) {
            nombre1 = (String) JOptionPane.showInputDialog(
                    null,
                    "Ya hay un carro con ese nombre, ingrese uno diferente:",
                    "",
                    JOptionPane.INFORMATION_MESSAGE,
                    normal,
                    null,
                    ""
            );

            if (nombre1 == null || nombre1.trim().isEmpty()) {
                nombre1 = "Carro 1";
                break;
            }
        }

        c1.setText(nombre1);
        Carro1.setName(nombre1);

    }//GEN-LAST:event_c1MouseClicked

    private void c2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MouseClicked
        nombre2 = (String) JOptionPane.showInputDialog(
                null,
                "Ingrese un nombre: ",
                "",
                JOptionPane.INFORMATION_MESSAGE,
                normal,
                null,
                ""
        );

        if (nombre2 == null || nombre2.trim().isEmpty()) {
            nombre2 = "Carro 2";
        }

        while (nombre2.equals(nombre1) || nombre2.equals(nombre3)) {
            nombre2 = (String) JOptionPane.showInputDialog(
                    null,
                    "Ya hay un carro con ese nombre, ingrese uno diferente:",
                    "",
                    JOptionPane.INFORMATION_MESSAGE,
                    normal,
                    null,
                    ""
            );

            if (nombre2 == null || nombre2.trim().isEmpty()) {
                nombre2 = "Carro 2";
                break;
            }
        }

        c2.setText(nombre2);
        Carro2.setName(nombre2);
    }//GEN-LAST:event_c2MouseClicked

    private void c3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3MouseClicked
        nombre3 = (String) JOptionPane.showInputDialog(
                null,
                "Ingrese un nombre: ",
                "",
                JOptionPane.INFORMATION_MESSAGE,
                normal,
                null,
                ""
        );

        if (nombre3 == null || nombre3.trim().isEmpty()) {
            nombre3 = "Carro 3";
        }

        while (nombre3.equals(nombre1) || nombre3.equals(nombre2)) {
            nombre3 = (String) JOptionPane.showInputDialog(
                    null,
                    "Ya hay un carro con ese nombre, ingrese uno diferente:",
                    "",
                    JOptionPane.INFORMATION_MESSAGE,
                    normal,
                    null,
                    ""
            );

            if (nombre3 == null || nombre3.trim().isEmpty()) {
                nombre3 = "Carro 3";
                break;
            }
        }

        c3.setText(nombre3);
        Carro3.setName(nombre3);

    }//GEN-LAST:event_c3MouseClicked

    private void c1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseEntered
        c1.setLocation(840, 350);
    }//GEN-LAST:event_c1MouseEntered

    private void c1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseExited
        c1.setLocation(840, 360);
    }//GEN-LAST:event_c1MouseExited

    private void c2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MouseEntered
        c2.setLocation(840, 440);
    }//GEN-LAST:event_c2MouseEntered

    private void c2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MouseExited
        c2.setLocation(840, 450);
    }//GEN-LAST:event_c2MouseExited

    private void c3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3MouseEntered
        c3.setLocation(840, 520);
    }//GEN-LAST:event_c3MouseEntered

    private void c3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3MouseExited
        c3.setLocation(840, 530);
    }//GEN-LAST:event_c3MouseExited

    private void marco3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marco3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_marco3MouseEntered

    private void ReiniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReiniciarMouseEntered
        Reiniciar.setBackground(new Color(153, 153, 255));
    }//GEN-LAST:event_ReiniciarMouseEntered

    private void ReiniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReiniciarMouseExited
        Reiniciar.setBackground(new Color(204, 204, 255));
    }//GEN-LAST:event_ReiniciarMouseExited

    public synchronized boolean isCarreraActiva() {
        return carreraActiva;
    }

    public synchronized void actualizarTablaPosiciones() {
        class PosCarro {

            String nombre;
            int x;

            PosCarro(String n, int x) {
                this.nombre = n;
                this.x = x;
            }
        }

        List<PosCarro> lista = new ArrayList<>();
        lista.add(new PosCarro(nombre1, Carro1.getX()));
        lista.add(new PosCarro(nombre2, Carro2.getX()));
        lista.add(new PosCarro(nombre3, Carro3.getX()));

        lista.sort((a, b) -> Integer.compare(b.x, a.x));

        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < lista.size(); i++) {
            PosCarro p = lista.get(i);
            sb.append("#").append(i + 1).append(". ")
                    .append(p.nombre)
                    .append(" (").append(p.x).append(")\n");
        }

        tabla.setText(sb.toString());
    }

    public synchronized void notificarGanador(JLabel carro) {

        if (!carreraActiva) {
            return;
        }

        String nombre = "";

        if (carro == Carro1) {
            nombre = nombre1;
        } else if (carro == Carro2) {
            nombre = nombre2;
        } else if (carro == Carro3) {
            nombre = nombre3;
        }

        if (!ordenLlegada.contains(nombre)) {
            ordenLlegada.add(nombre);
        }

        // Cuando llegan los 3 carros termina la carrera
        if (ordenLlegada.size() == 3) {
            carreraActiva = false;

            // Actualizar tabla final con ranking
            StringBuilder sbTabla = new StringBuilder();
            for (int i = 0; i < ordenLlegada.size(); i++) {
                sbTabla.append("#").append(i + 1).append(". ")
                        .append(ordenLlegada.get(i)).append("\n");
            }
            tabla.setText(sbTabla.toString());

            //Mostrar los resultados
            StringBuilder sb = new StringBuilder("Resultados finales:\n\n");
            for (int i = 0; i < ordenLlegada.size(); i++) {
                sb.append(i + 1).append("°. ")
                        .append(ordenLlegada.get(i)).append("\n");
            }

            mostrarDialogoBonito(sb.toString(), "", carrito);

            // Resetea las posiciones
            Carro1.setLocation(30, 20);
            Carro2.setLocation(30, 100);
            Carro3.setLocation(30, 170);

            Reiniciar.setEnabled(true);
        }
    }

    // Inicia la carrera: resetea todo y arranca los hilos
    private void iniciarCarrera() {

        if (carreraActiva) {
            return;
        }

        Reiniciar.setEnabled(false);
        tabla.setText("");

        ordenLlegada.clear();
        carreraActiva = true;

        Carro1.setLocation(30, 20);
        Carro2.setLocation(30, 100);
        Carro3.setLocation(30, 170);

        t1 = new CarroThread(Carro1, MAX_POSICION, this);
        t2 = new CarroThread(Carro2, MAX_POSICION, this);
        t3 = new CarroThread(Carro3, MAX_POSICION, this);

        t1.start();
        t2.start();
        t3.start();
    }

    public void mostrarDialogoBonito(String mensaje, String titulo, Icon icono) {

        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.setBackground(new Color(245, 245, 255));
        panel.setBorder(BorderFactory.createEmptyBorder(20, 30, 20, 30));

        final float[] hue = {0f};
        Timer bordeTimer = new Timer(40, e -> {
            hue[0] += 0.01f;
            if (hue[0] > 1) {
                hue[0] = 0;
            }
            Color rainbow = Color.getHSBColor(hue[0], 1f, 1f);
            panel.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(rainbow, 4, true),
                    BorderFactory.createEmptyBorder(20, 30, 20, 30)
            ));
            panel.repaint();
        });
        bordeTimer.start();

        JLabel texto = new JLabel(
                "<html><div style='width:260px; text-align:center;'>"
                + mensaje.replace("\n", "<br>")
                + "</div></html>",
                icono,
                JLabel.CENTER
        );
        texto.setFont(new Font("Segoe UI", Font.PLAIN, 15));
        texto.setForeground(new Color(60, 60, 60));
        texto.setAlignmentX(JLabel.CENTER_ALIGNMENT);

        panel.add(texto);
        panel.add(Box.createVerticalStrut(15));

        JButton ok = new JButton("OK");
        ok.setFont(new Font("Segoe UI", Font.BOLD, 13));
        ok.setPreferredSize(new Dimension(50, 36));
        ok.setMaximumSize(new Dimension(50, 36));
        ok.setFocusPainted(false);
        ok.setBackground(new Color(210, 200, 255));
        ok.setAlignmentX(JButton.CENTER_ALIGNMENT);

        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                ok.setBackground(new Color(225, 215, 255));
            }

            public void mouseExited(java.awt.event.MouseEvent e) {
                ok.setBackground(new Color(210, 200, 255));
            }
        });

        panel.add(ok);

        JDialog dialog = new JDialog(this, titulo, true);
        dialog.setUndecorated(true);
        dialog.setContentPane(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(this);

        dialog.getRootPane()
                .getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(KeyStroke.getKeyStroke("ESCAPE"), "none");

        ok.addActionListener(e -> {
            bordeTimer.stop();
            dialog.dispose();
        });

        dialog.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carreras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carro1;
    private javax.swing.JLabel Carro2;
    private javax.swing.JLabel Carro3;
    private javax.swing.JButton Reiniciar;
    private javax.swing.JLabel arbol;
    private javax.swing.JLabel arbol1;
    private javax.swing.JLabel arbol3;
    private javax.swing.JLabel arbol4;
    private javax.swing.JLabel arbol5;
    private javax.swing.JLabel arbol6;
    private javax.swing.JLabel arbol7;
    private javax.swing.JLabel arbol8;
    private javax.swing.JLabel arbol9;
    private javax.swing.JLabel bandera;
    private javax.swing.JLabel bomba;
    private javax.swing.JLabel bomba1;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel flechas;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel gente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel line;
    private javax.swing.JPanel line1;
    private javax.swing.JLabel marco;
    private javax.swing.JLabel marco1;
    private javax.swing.JLabel marco2;
    private javax.swing.JLabel marco3;
    private javax.swing.JLabel paddock;
    private javax.swing.JLabel pasto;
    private javax.swing.JLabel pasto10;
    private javax.swing.JLabel pasto11;
    private javax.swing.JLabel pasto12;
    private javax.swing.JLabel pasto13;
    private javax.swing.JLabel pasto3;
    private javax.swing.JLabel pasto4;
    private javax.swing.JLabel pasto8;
    private javax.swing.JLabel pasto9;
    private javax.swing.JPanel pista;
    private javax.swing.JTextArea tabla;
    private javax.swing.JLabel volver;
    // End of variables declaration//GEN-END:variables
}
