/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juegos;

import java.awt.Toolkit;
import java.util.Random;
import java.util.Stack;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class rompecabezas extends javax.swing.JFrame {

    int aleatorios[] = new int[9];

    /**
     * Creates new form rompecabezas
     */
    public rompecabezas() {
        initComponents();
        this.setLocationRelativeTo(null);
        nueve.setVisible(false);
        mov.setText("" + c);
        numeros();

        uno.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[0] + ".png")));
        dos.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[1] + ".png")));
        tres.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[2] + ".png")));
        cuatro.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[3] + ".png")));
        cinco.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[4] + ".png")));
        seis.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[5] + ".png")));
        siete.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[6] + ".png")));
        ocho.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[7] + ".png")));
        nueve.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[8] + ".png")));

        flechas.setVisible(false);
        setIcon();
    }
    
    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("log.png")));
    }

    public Icon uno1 = new ImageIcon(getClass().getResource("puzzleimg\\1.png"));
    public Icon dos2 = new ImageIcon(getClass().getResource("puzzleimg\\2.png"));
    public Icon tres3 = new ImageIcon(getClass().getResource("puzzleimg\\3.png"));
    public Icon cuatro4 = new ImageIcon(getClass().getResource("puzzleimg\\4.png"));
    public Icon cinco5 = new ImageIcon(getClass().getResource("puzzleimg\\5.png"));
    public Icon seis6 = new ImageIcon(getClass().getResource("puzzleimg\\6.png"));
    public Icon siete7 = new ImageIcon(getClass().getResource("puzzleimg\\7.png"));
    public Icon ocho8 = new ImageIcon(getClass().getResource("puzzleimg\\8.png"));
    public Icon nueve9 = new ImageIcon(getClass().getResource("puzzleimg\\9.png"));
    public Icon icon = new ImageIcon(getClass().getResource("sopaimg\\cat.gif"));

    public static int c = 0;

    public void numeros() {
        Stack<Integer> numeros = new Stack<Integer>();
        Random r = new Random();

        int aleatorio;

        for (int i = 0; i < 9; i++) {
            aleatorio = (int) (r.nextDouble() * 9 + 1);

            while (numeros.contains(aleatorio)) {
                aleatorio = (int) (r.nextDouble() * 9 + 1);
            }
            numeros.push(aleatorio);
            aleatorios[i] = aleatorio;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        marco1 = new javax.swing.JLabel();
        imagen = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 1000), new java.awt.Dimension(0, 1000), new java.awt.Dimension(32767, 1000));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(1000, 0), new java.awt.Dimension(1000, 0), new java.awt.Dimension(1000, 32767));
        mov = new javax.swing.JLabel();
        heart = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        uno = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        volver = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        flechas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        marco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(46, 44, 48));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/corgif.gif"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/yellowstars.gif"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 490, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/corgif.gif"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/yellowstars.gif"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 490, -1, -1));

        jButton3.setBackground(new java.awt.Color(190, 190, 252));
        jButton3.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton3.setText("Completar");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 140, 50));

        jButton2.setBackground(new java.awt.Color(190, 190, 252));
        jButton2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton2.setText("Meclar");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 140, 50));

        jButton1.setBackground(new java.awt.Color(190, 190, 252));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton1.setText("Reiniciar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 140, 50));

        marco1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(141, 237, 230), new java.awt.Color(236, 203, 237), new java.awt.Color(204, 51, 255), new java.awt.Color(208, 229, 253)));
        jPanel1.add(marco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 260, 200));

        imagen.setBackground(new java.awt.Color(51, 51, 51));
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/im.png"))); // NOI18N
        imagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagenMouseClicked(evt);
            }
        });
        imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenActionPerformed(evt);
            }
        });
        jPanel1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 260, 200));
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, -240, 30, 880));
        jPanel1.add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1130, 30));

        mov.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        mov.setForeground(new java.awt.Color(255, 255, 255));
        mov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mov.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(mov, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 260, 60));

        heart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/wings.gif"))); // NOI18N
        heart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                heartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                heartMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                heartMousePressed(evt);
            }
        });
        jPanel1.add(heart, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.GridLayout(3, 3));

        uno.setBackground(new java.awt.Color(255, 204, 255));
        uno.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/1.png"))); // NOI18N
        uno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(242, 242, 242), java.awt.Color.lightGray, new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));
        uno.setFocusCycleRoot(true);
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });
        jPanel2.add(uno);

        dos.setBackground(new java.awt.Color(255, 204, 255));
        dos.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        dos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/2.png"))); // NOI18N
        dos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(242, 242, 242), java.awt.Color.lightGray, new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));
        dos.setFocusCycleRoot(true);
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });
        jPanel2.add(dos);

        tres.setBackground(new java.awt.Color(255, 204, 255));
        tres.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        tres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/3.png"))); // NOI18N
        tres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(242, 242, 242), java.awt.Color.lightGray, new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));
        tres.setFocusCycleRoot(true);
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        jPanel2.add(tres);

        cuatro.setBackground(new java.awt.Color(255, 204, 255));
        cuatro.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        cuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/4.png"))); // NOI18N
        cuatro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(242, 242, 242), java.awt.Color.lightGray, new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));
        cuatro.setFocusCycleRoot(true);
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });
        jPanel2.add(cuatro);

        cinco.setBackground(new java.awt.Color(255, 204, 255));
        cinco.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        cinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/5.png"))); // NOI18N
        cinco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(242, 242, 242), java.awt.Color.lightGray, new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));
        cinco.setFocusCycleRoot(true);
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });
        jPanel2.add(cinco);

        seis.setBackground(new java.awt.Color(255, 204, 255));
        seis.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        seis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/6.png"))); // NOI18N
        seis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(242, 242, 242), java.awt.Color.lightGray, new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));
        seis.setFocusCycleRoot(true);
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        jPanel2.add(seis);

        siete.setBackground(new java.awt.Color(255, 204, 255));
        siete.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        siete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/7.png"))); // NOI18N
        siete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(242, 242, 242), java.awt.Color.lightGray, new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));
        siete.setFocusCycleRoot(true);
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });
        jPanel2.add(siete);

        ocho.setBackground(new java.awt.Color(255, 204, 255));
        ocho.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        ocho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/8.png"))); // NOI18N
        ocho.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(242, 242, 242), java.awt.Color.lightGray, new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });
        jPanel2.add(ocho);

        nueve.setBackground(new java.awt.Color(255, 204, 255));
        nueve.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        nueve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/9.png"))); // NOI18N
        nueve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(242, 242, 242), java.awt.Color.lightGray, new java.awt.Color(242, 242, 242), new java.awt.Color(242, 242, 242)));
        nueve.setFocusCycleRoot(true);
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });
        jPanel2.add(nueve);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 110, 460, 380));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 70, 30));

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Movimientos: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 190, 68));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/db277az-77f26b0f-8494-454f-bff2-21d2ff4d723b (1).png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 260, 110));

        volver.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("Volver");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMouseExited(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 610, 60, -1));

        jLabel14.setFont(new java.awt.Font("SimSun", 0, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Referencia");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 260, -1));

        flechas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        flechas.setForeground(new java.awt.Color(255, 255, 255));
        flechas.setText("<<--------");
        jPanel1.add(flechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 630, 80, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/pinkyc.gif"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1018, 608, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/yellowstars.gif"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/corgif.gif"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/yellowstars.gif"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/corgif.gif"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 500, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/yellowstars.gif"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, -1, -1));

        jLabel15.setFont(new java.awt.Font("SimSun", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Rompecabezas");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 50, 460, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/yellowstars.gif"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/corgif.gif"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/yellowstars.gif"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/corgif.gif"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/puzzleimg/yellowstars.gif"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 490, -1, -1));

        marco.setBackground(new java.awt.Color(255, 204, 255));
        marco.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        marco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(141, 237, 230), new java.awt.Color(236, 203, 237), new java.awt.Color(204, 51, 255), new java.awt.Color(208, 229, 253)));
        jPanel1.add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 1100, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        if (dos.isVisible() == false) {
            dos.setText(uno.getText());
            dos.setIcon(uno.getIcon());
            uno.setVisible(false);
            uno.setIcon(null);
            dos.setVisible(true);
            c++;
            mov.setText("" + c);

        }

        if (tres.isVisible() == false) {
            tres.setText(uno.getText());
            tres.setIcon(uno.getIcon());
            uno.setVisible(false);
            uno.setIcon(null);
            tres.setVisible(true);
            c++;
            mov.setText("" + c);
        }

        if (cuatro.isVisible() == false) {
            cuatro.setText(uno.getText());
            cuatro.setIcon(uno.getIcon());
            uno.setVisible(false);
            uno.setIcon(null);
            cuatro.setVisible(true);
            c++;
            mov.setText("" + c);
        }
    }//GEN-LAST:event_unoActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed

        if (cinco.isVisible() == false) {
            cinco.setText(dos.getText());
            cinco.setIcon(dos.getIcon());
            dos.setVisible(false);
            dos.setIcon(null);
            cinco.setVisible(true);
            c++;
            mov.setText("" + c);
        }

        if (tres.isVisible() == false) {
            tres.setText(dos.getText());
            tres.setIcon(dos.getIcon());
            dos.setVisible(false);
            dos.setIcon(null);
            tres.setVisible(true);
            c++;
            mov.setText("" + c);
        }

        if (uno.isVisible() == false) {
            uno.setText(dos.getText());
            uno.setIcon(dos.getIcon());
            dos.setVisible(false);
            dos.setIcon(null);
            uno.setVisible(true);
            c++;
            mov.setText("" + c);
        }
    }//GEN-LAST:event_dosActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        if (dos.isVisible() == false) {
            dos.setText(tres.getText());
            dos.setIcon(tres.getIcon());
            tres.setVisible(false);
            tres.setIcon(null);
            dos.setVisible(true);
            c++;
            mov.setText("" + c);
        }

        if (seis.isVisible() == false) {
            seis.setText(tres.getText());
            seis.setIcon(tres.getIcon());
            tres.setVisible(false);
            tres.setIcon(null);
            seis.setVisible(true);
            c++;
            mov.setText("" + c);
        }
    }//GEN-LAST:event_tresActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        if (siete.isVisible() == false) {
            siete.setText(cuatro.getText());
            siete.setIcon(cuatro.getIcon());
            cuatro.setVisible(false);
            cuatro.setIcon(null);
            siete.setVisible(true);
            c++;
            mov.setText("" + c);
        }

        if (cinco.isVisible() == false) {
            cinco.setText(cuatro.getText());
            cinco.setIcon(cuatro.getIcon());
            cuatro.setVisible(false);
            cuatro.setIcon(null);
            cinco.setVisible(true);
            c++;
            mov.setText("" + c);

        }

        if (uno.isVisible() == false) {
            uno.setText(cuatro.getText());
            uno.setIcon(cuatro.getIcon());
            cuatro.setVisible(false);
            cuatro.setIcon(null);
            uno.setVisible(true);
            c++;
            mov.setText("" + c);
        }
    }//GEN-LAST:event_cuatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        if (seis.isVisible() == false) {
            seis.setText(cinco.getText());
            seis.setIcon(cinco.getIcon());
            cinco.setVisible(false);
            cinco.setIcon(null);
            seis.setVisible(true);
            c++;
            mov.setText("" + c);
        }

        if (cuatro.isVisible() == false) {
            cuatro.setText(cinco.getText());
            cuatro.setIcon(cinco.getIcon());
            cinco.setVisible(false);
            cinco.setIcon(null);
            cuatro.setVisible(true);
            c++;
            mov.setText("" + c);
        }

        if (dos.isVisible() == false) {
            dos.setText(cinco.getText());
            dos.setIcon(cinco.getIcon());
            cinco.setVisible(false);
            cinco.setIcon(null);
            dos.setVisible(true);
            c++;
            mov.setText("" + c);
        }

        if (ocho.isVisible() == false) {
            ocho.setText(cinco.getText());
            ocho.setIcon(cinco.getIcon());
            cinco.setVisible(false);
            cinco.setIcon(null);
            ocho.setVisible(true);
            c++;
            mov.setText("" + c);
        }
    }//GEN-LAST:event_cincoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        if (nueve.isVisible() == false) {
            nueve.setText(seis.getText());
            nueve.setIcon(seis.getIcon());
            seis.setVisible(false);
            seis.setIcon(null);
            nueve.setVisible(true);
            c++;
            mov.setText("" + c);
        }

        if (cinco.isVisible() == false) {
            cinco.setText(seis.getText());
            cinco.setIcon(seis.getIcon());
            seis.setVisible(false);
            seis.setIcon(null);
            cinco.setVisible(true);
            c++;
            mov.setText("" + c);
        }

        if (tres.isVisible() == false) {
            tres.setText(seis.getText());
            tres.setIcon(seis.getIcon());
            seis.setVisible(false);
            seis.setIcon(null);
            tres.setVisible(true);
            c++;
            mov.setText("" + c);
        }
    }//GEN-LAST:event_seisActionPerformed

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
        if (ocho.isVisible() == false) {
            ocho.setText(siete.getText());
            ocho.setIcon(siete.getIcon());
            siete.setVisible(false);
            siete.setIcon(null);
            ocho.setVisible(true);
            c++;
            mov.setText("" + c);
        }

        if (cuatro.isVisible() == false) {
            cuatro.setText(siete.getText());
            cuatro.setIcon(siete.getIcon());
            siete.setVisible(false);
            siete.setIcon(null);
            cuatro.setVisible(true);
            c++;
            mov.setText("" + c);
        }
    }//GEN-LAST:event_sieteActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        if (nueve.isVisible() == false) {
            nueve.setText(ocho.getText());
            nueve.setIcon(ocho.getIcon());
            ocho.setVisible(false);
            ocho.setIcon(null);
            nueve.setVisible(true);
            c++;
            mov.setText("" + c);
        }

        if (siete.isVisible() == false) {
            siete.setText(ocho.getText());
            siete.setIcon(ocho.getIcon());
            ocho.setVisible(false);
            ocho.setIcon(null);
            siete.setVisible(true);
            c++;
            mov.setText("" + c);
        }

        if (cinco.isVisible() == false) {
            cinco.setText(ocho.getText());
            cinco.setIcon(ocho.getIcon());
            ocho.setVisible(false);
            ocho.setIcon(null);
            cinco.setVisible(true);
            c++;
            mov.setText("" + c);
        }
    }//GEN-LAST:event_ochoActionPerformed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
        if (seis.isVisible() == false) {
            seis.setText(nueve.getText());
            seis.setIcon(nueve.getIcon());
            nueve.setVisible(false);
            nueve.setIcon(null);
            seis.setVisible(true);
            c++;
            mov.setText("" + c);
        }

        if (ocho.isVisible() == false) {
            ocho.setText(nueve.getText());
            ocho.setIcon(nueve.getIcon());
            nueve.setVisible(false);
            nueve.setIcon(null);
            ocho.setVisible(true);
            c++;
            mov.setText("" + c);
        }
    }//GEN-LAST:event_nueveActionPerformed

    private void imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenActionPerformed

    }//GEN-LAST:event_imagenActionPerformed

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked

        main.Menu menu = new main.Menu();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_volverMouseClicked

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        flechas.setVisible(true);
    }//GEN-LAST:event_volverMouseEntered

    private void volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseExited
        flechas.setVisible(false);
    }//GEN-LAST:event_volverMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        uno.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\1.png")));
        dos.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\2.png")));
        tres.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\3.png")));
        cuatro.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\4.png")));
        cinco.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\5.png")));
        seis.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\6.png")));
        siete.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\7.png")));
        ocho.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\8.png")));
        nueve.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\9.png")));

        JOptionPane.showMessageDialog(null, "Felicidades, has completado el rompecabezas!", "Rompecabezas", JOptionPane.INFORMATION_MESSAGE, icon);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        uno.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[0] + ".png")));
        dos.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[1] + ".png")));
        tres.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[2] + ".png")));
        cuatro.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[3] + ".png")));
        cinco.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[4] + ".png")));
        seis.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[5] + ".png")));
        siete.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[6] + ".png")));
        ocho.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[7] + ".png")));
        nueve.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[8] + ".png")));

        c = 0;
        mov.setText("" + c);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        numeros();
        uno.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[0] + ".png")));
        dos.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[1] + ".png")));
        tres.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[2] + ".png")));
        cuatro.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[3] + ".png")));
        cinco.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[4] + ".png")));
        seis.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[5] + ".png")));
        siete.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[6] + ".png")));
        ocho.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[7] + ".png")));
        nueve.setIcon(new ImageIcon(getClass().getResource("puzzleimg\\" + aleatorios[8] + ".png")));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void heartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heartMouseEntered
        heart.setLocation(570, 395);
    }//GEN-LAST:event_heartMouseEntered

    private void heartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heartMousePressed

    }//GEN-LAST:event_heartMousePressed

    private void heartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heartMouseExited
        heart.setLocation(570, 400);
    }//GEN-LAST:event_heartMouseExited

    private void imagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenMouseClicked

    }//GEN-LAST:event_imagenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rompecabezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rompecabezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rompecabezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rompecabezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rompecabezas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton dos;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel flechas;
    private javax.swing.JLabel heart;
    private javax.swing.JButton imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel marco;
    private javax.swing.JLabel marco1;
    private javax.swing.JLabel mov;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    private javax.swing.JLabel volver;
    // End of variables declaration//GEN-END:variables
}
