/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juegos;

import static java.awt.Color.pink;
import static java.awt.Color.white;
import java.awt.Toolkit;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static juegos.blackjack.cartaOculta;

/**
 *
 * @author andre
 */
public class serpientes_y_escaleras extends javax.swing.JFrame {

    /**
     * Creates new form serpientes_y_escaleras
     */
    public serpientes_y_escaleras() {
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        reinicio.setEnabled(false);
        setIcon();
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/main/log.png")));
    }

    public int x, y, dado, casillas = 9, casilla = 1, op, res, da = 0;
    public int xx, yy, casillas2 = 9, casilla2 = 1, op2, res2;

    public Icon uno = new ImageIcon(getClass().getResource("/juegos/serpientes/1.png"));
    public Icon dos = new ImageIcon(getClass().getResource("/juegos/serpientes/2.png"));
    public Icon tres = new ImageIcon(getClass().getResource("/juegos/serpientes/3.png"));
    public Icon cuatro = new ImageIcon(getClass().getResource("/juegos/serpientes/4.png"));
    public Icon cinco = new ImageIcon(getClass().getResource("/juegos/serpientes/5.png"));
    public Icon seis = new ImageIcon(getClass().getResource("/juegos/serpientes/6.png"));
    public Icon dados = new ImageIcon(getClass().getResource("/juegos/serpientes/dado.gif"));
    public Icon win = new ImageIcon(getClass().getResource("/juegos/sopaimg/happy_cat.gif"));
    public String name1 = "Player 1";
    public String name2 = "Player 2";

    public void iniciar() {
        ficha1.setLocation(40, 540);
        ficha2.setLocation(40, 540);
        reinicio.setEnabled(false);
        x = ficha1.getX();
        y = ficha1.getY();
        xx = ficha2.getX();
        yy = ficha2.getY();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reinicio = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        p2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        j1 = new javax.swing.JLabel();
        num2 = new javax.swing.JLabel();
        num = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        j2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        marco1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 800), new java.awt.Dimension(0, 1000), new java.awt.Dimension(32767, 1000));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(1000, 0), new java.awt.Dimension(1000, 0), new java.awt.Dimension(1000, 32767));
        volver = new javax.swing.JLabel();
        p1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        flechas = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        marco = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ficha1 = new javax.swing.JLabel();
        ficha2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Serpientes y Escaleras");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(46, 44, 48));
        jPanel1.setMinimumSize(new java.awt.Dimension(1130, 690));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reinicio.setBackground(new java.awt.Color(204, 204, 255));
        reinicio.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        reinicio.setText("Reiniciar");
        reinicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        reinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinicioActionPerformed(evt);
            }
        });
        jPanel1.add(reinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 530, 150, 60));

        jLabel16.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("DADO");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 80, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("DADO");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 80, 80, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ingrese Jugador 2:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 220, 30));

        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        jPanel1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 330, 200, 30));

        jButton1.setText("Cambiar");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 380, 140, 30));

        j1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        j1.setForeground(new java.awt.Color(255, 255, 255));
        j1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/ficha.png"))); // NOI18N
        j1.setText("Player 1");
        jPanel1.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, -1));

        num2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/dado.gif"))); // NOI18N
        jPanel1.add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, -1, 70));

        num.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/dado.gif"))); // NOI18N
        jPanel1.add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, 70));

        b2.setText("Player 2");
        b2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 80, 30));

        b1.setText("Player 1");
        b1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 80, 30));

        j2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        j2.setForeground(new java.awt.Color(255, 255, 255));
        j2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/ficha 2.png"))); // NOI18N
        j2.setText("Player 2");
        jPanel1.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, -1, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/flowers.gif"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/flowers.gif"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/flowers.gif"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/flowers.gif"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/flowers.gif"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/flowers.gif"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 630, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/flowers.gif"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 630, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/flowers.gif"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/flowers.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/flowers.gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, -1, -1));

        marco1.setBackground(new java.awt.Color(255, 204, 255));
        marco1.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        marco1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(marco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 562, 560));
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, 20, 690));
        jPanel1.add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1130, 20));

        volver.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("VOLVER");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMouseExited(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1038, 610, 60, -1));

        p1.setToolTipText("Nombre");
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 182, 200, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/blackjackimg/pinkyc.gif"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 605, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ingrese Jugador 1:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 220, 30));

        flechas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        flechas.setForeground(new java.awt.Color(255, 255, 255));
        flechas.setText("<<--------");
        jPanel1.add(flechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1012, 630, 80, -1));

        jButton2.setText("Cambiar");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, 140, 30));

        marco.setBackground(new java.awt.Color(255, 204, 255));
        marco.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        marco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 1100, 660));

        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 250, 360));

        jPanel2.setBackground(new java.awt.Color(46, 44, 48));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ficha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/ficha.png"))); // NOI18N
        jPanel2.add(ficha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        ficha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/ficha 2.png"))); // NOI18N
        jPanel2.add(ficha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegos/serpientes/tablero.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 592, 600));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked

        main.Menu menu = new main.Menu();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_volverMouseClicked

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        flechas.setVisible(true);
        volver.setForeground(pink);
        flechas.setForeground(pink);
    }//GEN-LAST:event_volverMouseEntered

    private void volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseExited
        flechas.setVisible(false);
        volver.setForeground(white);
        flechas.setForeground(white);
    }//GEN-LAST:event_volverMouseExited

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed

        dado();
        da = dado;
        mover();
        if (da == 1) {
            dados = new ImageIcon(getClass().getResource("/juegos/serpientes/1.png"));
        }
        if (da == 2) {
            dados = new ImageIcon(getClass().getResource("/juegos/serpientes/2.png"));
        }
        if (da == 3) {
            dados = new ImageIcon(getClass().getResource("/juegos/serpientes/3.png"));
        }
        if (da == 4) {
            dados = new ImageIcon(getClass().getResource("/juegos/serpientes/4.png"));
        }
        if (da == 5) {
            dados = new ImageIcon(getClass().getResource("/juegos/serpientes/5.png"));
        }
        if (da == 6) {
            dados = new ImageIcon(getClass().getResource("/juegos/serpientes/6.png"));
        }
        JOptionPane.showMessageDialog(null, "" + dado, "DADO:", JOptionPane.INFORMATION_MESSAGE, dados);

    }//GEN-LAST:event_b1ActionPerformed


    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        dado();
        da = dado;
        mover2();
        if (da == 1) {
            dados = new ImageIcon(getClass().getResource("/juegos/serpientes/1.png"));
        }
        if (da == 2) {
            dados = new ImageIcon(getClass().getResource("/juegos/serpientes/2.png"));
        }
        if (da == 3) {
            dados = new ImageIcon(getClass().getResource("/juegos/serpientes/3.png"));
        }
        if (da == 4) {
            dados = new ImageIcon(getClass().getResource("/juegos/serpientes/4.png"));
        }
        if (da == 5) {
            dados = new ImageIcon(getClass().getResource("/juegos/serpientes/5.png"));
        }
        if (da == 6) {
            dados = new ImageIcon(getClass().getResource("/juegos/serpientes/6.png"));
        }
        JOptionPane.showMessageDialog(null, "" + dado, "DADO:", JOptionPane.INFORMATION_MESSAGE, dados);
    }//GEN-LAST:event_b2ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        name2 = p2.getText();
        j2.setText(name2);
        b2.setText(name2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        name1 = p1.getText();
        j1.setText(name1);
        b1.setText(name1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed

    private void reinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinicioActionPerformed
        iniciar();
    }//GEN-LAST:event_reinicioActionPerformed

    public void mover() {

        x = ficha1.getX();
        y = ficha1.getY();

        if (x <= 488 && y == 540 && dado <= casillas) {
            ficha1.setLocation(x + 56 * dado, y);
            casillas = casillas - dado;
            casilla = casilla + dado;

        } else if (x >= 264 && y == 540 && dado > casillas) {

            op = 10 - casilla;
            res = (dado - op) - 1;
            ficha1.setLocation(x + 56 * op, y);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x, y - 56);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x - 56 * (dado - casillas - 1), y);
            x = ficha1.getX();
            y = ficha1.getY();

            casilla = dado - casillas;
            casillas = 10 - (dado - casillas);

        } else if (x <= 544 && y == 484 && dado <= casillas) {
            ficha1.setLocation(x - 56 * dado, y);
            casillas = casillas - dado;
            casilla = casilla + dado;

        } else if (x <= 488 && y == 484 && dado > casillas) {

            op = 10 - casilla;
            res = (dado - op) - 1;
            ficha1.setLocation(x - 56 * op, y);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x, y - 56);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x + 56 * (dado - casillas - 1), y);
            x = ficha1.getX();
            y = ficha1.getY();

            casilla = dado - casillas;
            casillas = 10 - (dado - casillas);

        } else if (x >= 40 && y == 484 && dado <= casillas) {
            ficha1.setLocation(x + 56 * dado, y);
            casillas = casillas - dado;
            casilla = casilla + dado;
        } else if (x <= 488 && y == 484 && dado > casillas) {

            op = 10 - casilla;
            res = (dado - op) - 1;
            ficha1.setLocation(x - 56 * op, y);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x, y - 56);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x + 56 * (dado - casillas - 1), y);
            x = ficha1.getX();
            y = ficha1.getY();

            casilla = dado - casillas;
            casillas = 10 - (dado - casillas);

        } else if (x <= 544 && y == 428 && dado <= casillas) {
            ficha1.setLocation(x + 56 * dado, y);
            casillas = casillas - dado;
            casilla = casilla + dado;

        } else if (x <= 544 && y == 428 && dado > casillas) {

            op = 10 - casilla;
            res = (dado - op) - 1;
            ficha1.setLocation(x + 56 * op, y);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x, y - 56);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x - 56 * (dado - casillas - 1), y);
            x = ficha1.getX();
            y = ficha1.getY();

            casilla = dado - casillas;
            casillas = 10 - (dado - casillas);

        } else if (x <= 544 && y == 372 && dado <= casillas) {
            ficha1.setLocation(x - 56 * dado, y);
            casillas = casillas - dado;
            casilla = casilla + dado;
        } else if (x <= 488 && y == 372 && dado > casillas) {

            op = 10 - casilla;
            res = (dado - op) - 1;
            ficha1.setLocation(x - 56 * op, y);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x, y - 56);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x + 56 * (dado - casillas - 1), y);
            x = ficha1.getX();
            y = ficha1.getY();

            casilla = dado - casillas;
            casillas = 10 - (dado - casillas);

        } else if (x >= 40 && y == 316 && dado <= casillas) {
            ficha1.setLocation(x + 56 * dado, y);
            casillas = casillas - dado;
            casilla = casilla + dado;
        } else if (x >= 264 && y == 316 && dado > casillas) {

            op = 10 - casilla;
            res = (dado - op) - 1;
            ficha1.setLocation(x + 56 * op, y);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x, y - 56);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x - 56 * (dado - casillas - 1), y);
            x = ficha1.getX();
            y = ficha1.getY();

            casilla = dado - casillas;
            casillas = 10 - (dado - casillas);

        } else if (x <= 544 && y == 260 && dado <= casillas) {
            ficha1.setLocation(x - 56 * dado, y);
            casillas = casillas - dado;
            casilla = casilla + dado;
        } else if (x <= 488 && y == 260 && dado > casillas) {

            op = 10 - casilla;
            res = (dado - op) - 1;
            ficha1.setLocation(x - 56 * op, y);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x, y - 56);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x + 56 * (dado - casillas - 1), y);
            x = ficha1.getX();
            y = ficha1.getY();

            casilla = dado - casillas;
            casillas = 10 - (dado - casillas);

        } else if (x >= 40 && y == 204 && dado <= casillas) {
            ficha1.setLocation(x + 56 * dado, y);
            casillas = casillas - dado;
            casilla = casilla + dado;
        } else if (x >= 264 && y == 204 && dado > casillas) {

            op = 10 - casilla;
            res = (dado - op) - 1;
            ficha1.setLocation(x + 56 * op, y);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x, y - 56);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x - 56 * (dado - casillas - 1), y);
            x = ficha1.getX();
            y = ficha1.getY();

            casilla = dado - casillas;
            casillas = 10 - (dado - casillas);

        } else if (x <= 544 && y == 148 && dado <= casillas) {
            ficha1.setLocation(x - 56 * dado, y);
            casillas = casillas - dado;
            casilla = casilla + dado;
        } else if (x <= 544 && y == 148 && dado > casillas) {

            op = 10 - casilla;
            res = (dado - op) - 1;
            ficha1.setLocation(x - 56 * op, y);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x, y - 56);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x + 56 * (dado - casillas - 1), y);
            x = ficha1.getX();
            y = ficha1.getY();

            casilla = dado - casillas;
            casillas = 10 - (dado - casillas);

        } else if (x >= 40 && y == 92 && dado <= casillas) {
            ficha1.setLocation(x + 56 * dado, y);
            casillas = casillas - dado;
            casilla = casilla + dado;
        } else if (x >= 264 && y == 92 && dado > casillas) {

            op = 10 - casilla;
            res = (dado - op) - 1;
            ficha1.setLocation(x + 56 * op, y);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x, y - 56);
            x = ficha1.getX();
            y = ficha1.getY();
            ficha1.setLocation(x - 56 * (dado - casillas - 1), y);
            x = ficha1.getX();
            y = ficha1.getY();

            casilla = dado - casillas;
            casillas = 10 - (dado - casillas);

        } else if (x <= 544 && y == 148 && dado <= casillas) {
            ficha1.setLocation(x - 56 * dado, y);
            casillas = casillas - dado;
            casilla = casilla + dado;
        } else if (x <= 544 && y == 36 && dado <= casillas) {
            ficha1.setLocation(x - 56 * dado, y);
            casillas = casillas - dado;
            casilla = casilla + dado;
        }

        x = ficha1.getX();
        y = ficha1.getY();
//
////        // Escaleras
        if (x == 96 && y == 540) {
            ficha1.setLocation(152, 372);
            casillas = 2;
            casilla = 8;

        }
        if (x == 376 && y == 540) {
            ficha1.setLocation(376, 484);
            casillas = 6;
            casilla = 4;
        }

        if (x == 432 && y == 540) {
            ficha1.setLocation(544, 372);
            casillas = 9;
            casilla = 1;
        }
        if (x == 320 && y == 484) {
            ficha1.setLocation(320, 428);
            casillas = 4;
            casilla = 6;
        }
        if (x == 432 && y == 428) {
            ficha1.setLocation(208, 92);
            casillas = 6;
            casilla = 4;
        }

        if (x == 40 && y == 428) {
            ficha1.setLocation(96, 316);
            casillas = 8;
            casilla = 2;
        }
        if (x == 264 && y == 372) {
            ficha1.setLocation(208, 316);
            casillas = 6;
            casilla = 4;
        }
        if (x == 544 && y == 260) {
            ficha1.setLocation(376, 204);
            casillas = 4;
            casilla = 6;
        }
        if (x == 152 && y == 148) {
            ficha1.setLocation(152, 36);
            casillas = 2;
            casilla = 8;
        }
        if (x == 376 && y == 92) {
            ficha1.setLocation(376, 36);
            casillas = 6;
            casilla = 4;
        }
        if (x == 544 && y == 148) {
            ficha1.setLocation(544, 36);
            casillas = 9;
            casilla = 1;
        }

//
////         Serpientes 
        if (x == 264 && y == 484) {
            ficha1.setLocation(264 + 56, 540);
            casillas = 4;
            casilla = 6;
        }
        if (x == 320 && y == 316) {
            ficha1.setLocation(264, 428);
            casillas = 5;
            casilla = 5;
        }
        if (x == 376 && y == 148) {
            ficha1.setLocation(432, 260);
            casillas = 7;
            casilla = 3;
        }
        if (x == 320 && y == 36) {
            ficha1.setLocation(320, 148);
            casillas = 5;
            casilla = 5;

        }
        if (x == 488 && y == 316) {
            ficha1.setLocation(544, 484);
            casillas = 9;
            casilla = 1;

        }

        if (x == 488 && y == 36) {
            ficha1.setLocation(432, 92);
            casillas = 2;
            casilla = 8;
        }
        if (x == 96 && y == 204) {
            ficha1.setLocation(96, 484);
            casillas = 1;
            casilla = 9;
        }
        if (x == 96 && y == 36) {
            ficha1.setLocation(40, 148);
            casillas = 0;
            casilla = 10;
        }
        if (x == 488 && y == 36) {
            ficha1.setLocation(432, 92);
            casillas = 2;
            casilla = 8;
        }
        if (x == 208 && y == 204) {
            ficha1.setLocation(40, 260);
            casillas = 0;
            casilla = 10;
        }
        if (x == 488 && y == 92) {
            ficha1.setLocation(432, 204);
            casillas = 2;
            casilla = 8;
        }
        b1.setEnabled(false);
        b2.setEnabled(true);

        if (x == 40 && y == 36) {
            JOptionPane.showMessageDialog(null, "Ha ganado " + name1, "GAME:", JOptionPane.INFORMATION_MESSAGE, win);
            reinicio.setEnabled(true);
        }
    }

    public void mover2() {
        xx = ficha2.getX();
        yy = ficha2.getY();

        if (xx <= 488 && yy == 540 && dado <= casillas2) {
            ficha2.setLocation(xx + 56 * dado, yy);
            casillas2 = casillas2 - dado;
            casilla2 = casilla2 + dado;

        } else if (xx >= 264 && yy == 540 && dado > casillas2) {

            op = 10 - casilla2;
            res = (dado - op) - 1;
            ficha2.setLocation(xx + 56 * op, yy);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx, yy - 56);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx - 56 * (dado - casillas2 - 1), yy);
            xx = ficha2.getX();
            yy = ficha2.getY();

            casilla2 = dado - casillas2;
            casillas2 = 10 - (dado - casillas2);

        } else if (xx <= 544 && yy == 484 && dado <= casillas2) {
            ficha2.setLocation(xx - 56 * dado, yy);
            casillas2 = casillas2 - dado;
            casilla2 = casilla2 + dado;

        } else if (xx <= 488 && yy == 484 && dado > casillas2) {

            op = 10 - casilla2;
            res = (dado - op) - 1;
            ficha2.setLocation(xx - 56 * op, yy);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx, yy - 56);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx + 56 * (dado - casillas2 - 1), yy);
            xx = ficha2.getX();
            yy = ficha2.getY();

            casilla2 = dado - casillas2;
            casillas2 = 10 - (dado - casillas2);

        } else if (xx >= 40 && yy == 484 && dado <= casillas2) {
            ficha2.setLocation(xx + 56 * dado, yy);
            casillas2 = casillas2 - dado;
            casilla2 = casilla2 + dado;
        } else if (xx <= 488 && yy == 484 && dado > casillas2) {

            op = 10 - casilla2;
            res = (dado - op) - 1;
            ficha1.setLocation(xx - 56 * op, yy);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx, yy - 56);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx + 56 * (dado - casillas2 - 1), yy);
            xx = ficha2.getX();
            yy = ficha2.getY();

            casilla2 = dado - casillas2;
            casillas2 = 10 - (dado - casillas2);

        } else if (xx <= 544 && yy == 428 && dado <= casillas2) {
            ficha2.setLocation(xx + 56 * dado, yy);
            casillas2 = casillas2 - dado;
            casilla2 = casilla2 + dado;

        } else if (xx <= 544 && yy == 428 && dado > casillas2) {

            op = 10 - casilla2;
            res = (dado - op) - 1;
            ficha2.setLocation(xx + 56 * op, yy);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx, yy - 56);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx - 56 * (dado - casillas2 - 1), yy);
            xx = ficha2.getX();
            yy = ficha2.getY();

            casilla2 = dado - casillas2;
            casillas2 = 10 - (dado - casillas2);

        } else if (xx <= 544 && yy == 372 && dado <= casillas2) {
            ficha2.setLocation(xx - 56 * dado, yy);
            casillas2 = casillas2 - dado;
            casilla2 = casilla2 + dado;
        } else if (xx <= 488 && yy == 372 && dado > casillas2) {

            op = 10 - casilla2;
            res = (dado - op) - 1;
            ficha2.setLocation(xx - 56 * op, yy);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx, yy - 56);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx + 56 * (dado - casillas2 - 1), yy);
            xx = ficha2.getX();
            yy = ficha2.getY();

            casilla2 = dado - casillas2;
            casillas2 = 10 - (dado - casillas2);

        } else if (xx >= 40 && yy == 316 && dado <= casillas2) {
            ficha2.setLocation(xx + 56 * dado, yy);
            casillas2 = casillas2 - dado;
            casilla2 = casilla2 + dado;
        } else if (xx >= 264 && yy == 316 && dado > casillas2) {

            op = 10 - casilla2;
            res = (dado - op) - 1;
            ficha2.setLocation(xx + 56 * op, yy);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx, yy - 56);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx - 56 * (dado - casillas2 - 1), yy);
            xx = ficha2.getX();
            yy = ficha2.getY();

            casilla2 = dado - casillas2;
            casillas2 = 10 - (dado - casillas2);

        } else if (xx <= 544 && yy == 260 && dado <= casillas2) {
            ficha2.setLocation(xx - 56 * dado, yy);
            casillas2 = casillas2 - dado;
            casilla2 = casilla2 + dado;
        } else if (xx <= 488 && yy == 260 && dado > casillas2) {

            op = 10 - casilla2;
            res = (dado - op) - 1;
            ficha2.setLocation(xx - 56 * op, yy);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx, yy - 56);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx + 56 * (dado - casillas2 - 1), yy);
            xx = ficha2.getX();
            yy = ficha2.getY();

            casilla2 = dado - casillas2;
            casillas2 = 10 - (dado - casillas2);

        } else if (xx >= 40 && yy == 204 && dado <= casillas2) {
            ficha2.setLocation(xx + 56 * dado, yy);
            casillas2 = casillas2 - dado;
            casilla2 = casilla2 + dado;
        } else if (xx >= 264 && yy == 204 && dado > casillas2) {

            op = 10 - casilla2;
            res = (dado - op) - 1;
            ficha2.setLocation(xx + 56 * op, yy);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx, yy - 56);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx - 56 * (dado - casillas2 - 1), yy);
            xx = ficha2.getX();
            yy = ficha2.getY();

            casilla2 = dado - casillas2;
            casillas2 = 10 - (dado - casillas2);

        } else if (xx <= 544 && yy == 148 && dado <= casillas2) {
            ficha2.setLocation(xx - 56 * dado, yy);
            casillas2 = casillas2 - dado;
            casilla2 = casilla2 + dado;
        } else if (xx <= 544 && yy == 148 && dado > casillas2) {

            op = 10 - casilla2;
            res = (dado - op) - 1;
            ficha2.setLocation(xx - 56 * op, yy);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx, yy - 56);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx + 56 * (dado - casillas2 - 1), yy);
            xx = ficha2.getX();
            yy = ficha2.getY();

            casilla2 = dado - casillas2;
            casillas2 = 10 - (dado - casillas2);

        } else if (xx >= 40 && yy == 92 && dado <= casillas2) {
            ficha2.setLocation(xx + 56 * dado, yy);
            casillas2 = casillas2 - dado;
            casilla2 = casilla2 + dado;
        } else if (xx >= 264 && yy == 92 && dado > casillas2) {

            op = 10 - casilla2;
            res = (dado - op) - 1;
            ficha2.setLocation(xx + 56 * op, yy);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx, yy - 56);
            xx = ficha2.getX();
            yy = ficha2.getY();
            ficha2.setLocation(xx - 56 * (dado - casillas2 - 1), yy);
            xx = ficha2.getX();
            yy = ficha2.getY();

            casilla2 = dado - casillas2;
            casillas2 = 10 - (dado - casillas2);

        } else if (xx <= 544 && yy == 148 && dado <= casillas2) {
            ficha2.setLocation(xx - 56 * dado, yy);
            casillas2 = casillas2 - dado;
            casilla2 = casilla2 + dado;
        } else if (xx <= 544 && yy == 36 && dado <= casillas2) {
            ficha2.setLocation(xx - 56 * dado, yy);
            casillas2 = casillas2 - dado;
            casilla2 = casilla2 + dado;
        }

        xx = ficha2.getX();
        yy = ficha2.getY();
//
////        // Escaleras
        if (xx == 96 && yy == 540) {
            ficha2.setLocation(152, 372);
            casillas2 = 2;
            casilla2 = 8;

        }
        if (xx == 376 && yy == 540) {
            ficha2.setLocation(376, 484);
            casillas2 = 6;
            casilla2 = 4;
        }

        if (xx == 432 && yy == 540) {
            ficha2.setLocation(544, 372);
            casillas2 = 9;
            casilla2 = 1;
        }
        if (xx == 320 && yy == 484) {
            ficha2.setLocation(320, 428);
            casillas2 = 4;
            casilla2 = 6;
        }
        if (xx == 432 && yy == 428) {
            ficha2.setLocation(208, 92);
            casillas2 = 6;
            casilla2 = 4;
        }

        if (xx == 40 && yy == 428) {
            ficha2.setLocation(96, 316);
            casillas2 = 8;
            casilla2 = 2;
        }
        if (xx == 264 && yy == 372) {
            ficha2.setLocation(208, 316);
            casillas2 = 6;
            casilla2 = 4;
        }
        if (xx == 544 && yy == 260) {
            ficha2.setLocation(376, 204);
            casillas2 = 4;
            casilla2 = 6;
        }
        if (xx == 152 && yy == 148) {
            ficha2.setLocation(152, 36);
            casillas2 = 2;
            casilla2 = 8;
        }
        if (xx == 376 && yy == 92) {
            ficha2.setLocation(376, 36);
            casillas2 = 6;
            casilla2 = 4;
        }
        if (xx == 544 && yy == 148) {
            ficha2.setLocation(544, 36);
            casillas2 = 9;
            casilla2 = 1;
        }

//
////         Serpientes 
        if (xx == 264 && yy == 484) {
            ficha2.setLocation(264 + 56, 540);
            casillas2 = 4;
            casilla2 = 6;
        }
        if (xx == 320 && yy == 316) {
            ficha2.setLocation(264, 428);
            casillas2 = 5;
            casilla2 = 5;
        }
        if (xx == 376 && yy == 148) {
            ficha2.setLocation(432, 260);
            casillas2 = 7;
            casilla2 = 3;
        }
        if (xx == 320 && yy == 36) {
            ficha2.setLocation(320, 148);
            casillas2 = 5;
            casilla2 = 5;

        }
        if (xx == 488 && yy == 316) {
            ficha2.setLocation(544, 484);
            casillas2 = 9;
            casilla2 = 1;

        }

        if (xx == 488 && yy == 36) {
            ficha2.setLocation(432, 92);
            casillas2 = 2;
            casilla2 = 8;
        }
        if (xx == 96 && yy == 204) {
            ficha2.setLocation(96, 484);
            casillas2 = 1;
            casilla2 = 9;
        }
        if (xx == 96 && yy == 36) {
            ficha2.setLocation(40, 148);
            casillas2 = 0;
            casilla2 = 10;
        }
        if (xx == 488 && yy == 36) {
            ficha2.setLocation(432, 92);
            casillas2 = 2;
            casilla2 = 8;
        }
        if (xx == 208 && yy == 204) {
            ficha2.setLocation(40, 260);
            casillas2 = 0;
            casilla2 = 10;
        }
        if (xx == 488 && yy == 92) {
            ficha2.setLocation(432, 204);
            casillas2 = 2;
            casilla2 = 8;
        }
        b2.setEnabled(false);
        b1.setEnabled(true);

        if (xx == 40 && yy == 36) {
            JOptionPane.showMessageDialog(null, "Ha ganado " + name2, "GAME:", JOptionPane.INFORMATION_MESSAGE, win);
            reinicio.setEnabled(true);
        }
    }

    public void dado() {

        Random r = new Random();

        dado = r.nextInt(6);
        dado = dado + 1;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(serpientes_y_escaleras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(serpientes_y_escaleras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(serpientes_y_escaleras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(serpientes_y_escaleras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new serpientes_y_escaleras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JLabel ficha1;
    private javax.swing.JLabel ficha2;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel flechas;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel marco;
    private javax.swing.JLabel marco1;
    private javax.swing.JLabel num;
    private javax.swing.JLabel num2;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JButton reinicio;
    private javax.swing.JLabel volver;
    // End of variables declaration//GEN-END:variables
}
